//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solidsoft.Reply.Gs1DigitalLinkLib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solidsoft.Reply.Gs1DigitalLinkLib.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}={1}&apos; is invalid. Non-GS1 key values must not be all-numeric..
        /// </summary>
        internal static string ErrorMsg01IsInvalidNonGs1KeyValuesMustNotBeAllNumeric {
            get {
                return ResourceManager.GetString("ErrorMsg01IsInvalidNonGs1KeyValuesMustNotBeAllNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}={1}&apos; is invalid. The parameter contains incorrectly unencoded characters..
        /// </summary>
        internal static string ErrorMsg01IsInvalidTheParameterContainsIncorrectlyUnencodedCharacters {
            get {
                return ResourceManager.GetString("ErrorMsg01IsInvalidTheParameterContainsIncorrectlyUnencodedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid. The fragment contains incorrectly unencoded characters..
        /// </summary>
        internal static string ErrorMsg0IsInvalidTheFragmentContainsIncorrectlyUnencodedCharacters {
            get {
                return ResourceManager.GetString("ErrorMsg0IsInvalidTheFragmentContainsIncorrectlyUnencodedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid. The value contains incorrectly unencoded characters..
        /// </summary>
        internal static string ErrorMsg0IsInvalidTheValueContainsIncorrectlyUnencodedCharacters {
            get {
                return ResourceManager.GetString("ErrorMsg0IsInvalidTheValueContainsIncorrectlyUnencodedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a recognised GS1 AI..
        /// </summary>
        internal static string ErrorMsg0IsNotARecognisedGs1Ai {
            get {
                return ResourceManager.GetString("ErrorMsg0IsNotARecognisedGs1Ai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid check digit was found for the primary identification key ({0}) {1}; the correct check digit should be {2} at position {3}..
        /// </summary>
        internal static string ErrorMsgAnInvalidCheckDigitWasFoundForThePrimaryIdentificationKey01TheCorrectCheckDigitShouldBe2AtPosition3 {
            get {
                return ResourceManager.GetString("ErrorMsgAnInvalidCheckDigitWasFoundForThePrimaryIdentificationKey01TheCorrectChec" +
                        "kDigitShouldBe2AtPosition3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input &apos;{0}&apos; to date conversion did not match valid YYMMDDhhmm pattern..
        /// </summary>
        internal static string ErrorMsgInput0ToDateConversionDidNotMatchValidYymmddhhmmPattern {
            get {
                return ResourceManager.GetString("ErrorMsgInput0ToDateConversionDidNotMatchValidYymmddhhmmPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input &apos;{0}&apos; to date conversion did not match valid YYMMDDhh[mm][ss] pattern..
        /// </summary>
        internal static string ErrorMsgInput0ToDateConversionDidNotMatchValidYymmddhhMmSsPattern {
            get {
                return ResourceManager.GetString("ErrorMsgInput0ToDateConversionDidNotMatchValidYymmddhhMmSsPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input &apos;{0}&apos; to date conversion did not match valid YYMMDD pattern..
        /// </summary>
        internal static string ErrorMsgInput0ToDateConversionDidNotMatchValidYymmddPattern {
            get {
                return ResourceManager.GetString("ErrorMsgInput0ToDateConversionDidNotMatchValidYymmddPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input date &apos;{0}&apos; invalid. DD too large for MM..
        /// </summary>
        internal static string ErrorMsgInputDate0InvalidDdTooLargeForMm {
            get {
                return ResourceManager.GetString("ErrorMsgInputDate0InvalidDdTooLargeForMm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sequence of key qualifiers found in the GS1 DigitalLink URI path information..
        /// </summary>
        internal static string ErrorMsgInvalidSequenceOfKeyQualifiersFoundInTheGs1DigitallinkUriPathInformation {
            get {
                return ResourceManager.GetString("ErrorMsgInvalidSequenceOfKeyQualifiersFoundInTheGs1DigitallinkUriPathInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid syntax for value {0} of ({1})..
        /// </summary>
        internal static string ErrorMsgInvalidSyntaxForValue0Of1 {
            get {
                return ResourceManager.GetString("ErrorMsgInvalidSyntaxForValue0Of1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid syntax for value of ({0}) : {1}. Expected {2} characters..
        /// </summary>
        internal static string ErrorMsgInvalidSyntaxForValueOf01Expected2Characters {
            get {
                return ResourceManager.GetString("ErrorMsgInvalidSyntaxForValueOf01Expected2Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No key identifier found in the GS1 DigitalLink URI path information..
        /// </summary>
        internal static string ErrorMsgNoKeyIdentifierFoundInTheGsDigitallinkUriPathInformation {
            get {
                return ResourceManager.GetString("ErrorMsgNoKeyIdentifierFoundInTheGsDigitallinkUriPathInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} param {1}.
        /// </summary>
        internal static string ErrorMsgPart0Param1 {
            get {
                return ResourceManager.GetString("ErrorMsgPart0Param1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (FATAL).
        /// </summary>
        internal static string ErrorMsgPartFatal {
            get {
                return ResourceManager.GetString("ErrorMsgPartFatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following issues were detected:.
        /// </summary>
        internal static string ErrorMsgPartTheFollowingIssuesWereDetected {
            get {
                return ResourceManager.GetString("ErrorMsgPartTheFollowingIssuesWereDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} parameter contains &apos;{1}&apos; as a fragment, but a fragment has been provided using the {2} parameter..
        /// </summary>
        internal static string ErrorMsgThe0ParameterContains1AsAFragmentButAFragmentHasBeenProvidedUsingThe2Parameter {
            get {
                return ResourceManager.GetString("ErrorMsgThe0ParameterContains1AsAFragmentButAFragmentHasBeenProvidedUsingThe2Para" +
                        "meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary of AIs ({0} is empty..
        /// </summary>
        internal static string ErrorMsgTheDictionaryOfAis0IsEmpty {
            get {
                return ResourceManager.GetString("ErrorMsgTheDictionaryOfAis0IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element string &apos;{0}&apos; does not represent GS1 Digital Link data..
        /// </summary>
        internal static string ErrorMsgTheElementString0DoesNotRepresentGs1DigitalLinkData {
            get {
                return ResourceManager.GetString("ErrorMsgTheElementString0DoesNotRepresentGs1DigitalLinkData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the element string &apos;{0}&apos; is not recognised..
        /// </summary>
        internal static string ErrorMsgTheFormatOfTheElementString0IsNotRecognised {
            get {
                return ResourceManager.GetString("ErrorMsgTheFormatOfTheElementString0IsNotRecognised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the form of the Digital Link..
        /// </summary>
        internal static string ErrorMsgUnableToDetermineTheFormOfTheDigitalLink {
            get {
                return ResourceManager.GetString("ErrorMsgUnableToDetermineTheFormOfTheDigitalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID CHECK DIGIT.
        /// </summary>
        internal static string ErrorTypeInvalidCheckDigit {
            get {
                return ResourceManager.GetString("ErrorTypeInvalidCheckDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID ELEMENT STRING.
        /// </summary>
        internal static string ErrorTypeInvalidElementString {
            get {
                return ResourceManager.GetString("ErrorTypeInvalidElementString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID FRAGMENT SPECIFIER.
        /// </summary>
        internal static string ErrorTypeInvalidFragmentSpecifier {
            get {
                return ResourceManager.GetString("ErrorTypeInvalidFragmentSpecifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID GS1 APPLICATION IDENTIFIER.
        /// </summary>
        internal static string ErrorTypeInvalidGs1ApplicationIdentifier {
            get {
                return ResourceManager.GetString("ErrorTypeInvalidGs1ApplicationIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID GS1 DIGITAL LINK.
        /// </summary>
        internal static string ErrorTypeInvalidGs1DigitalLink {
            get {
                return ResourceManager.GetString("ErrorTypeInvalidGs1DigitalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID QUERY STRING CONTENT.
        /// </summary>
        internal static string ErrorTypeInvalidQueryStringContent {
            get {
                return ResourceManager.GetString("ErrorTypeInvalidQueryStringContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID QUERY STRING KEY-VALUE PAIR.
        /// </summary>
        internal static string ErrorTypeInvalidQueryStringKeyValuePair {
            get {
                return ResourceManager.GetString("ErrorTypeInvalidQueryStringKeyValuePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYNTAX ERROR.
        /// </summary>
        internal static string ErrorTypeSyntaxError {
            get {
                return ResourceManager.GetString("ErrorTypeSyntaxError", resourceCulture);
            }
        }
    }
}
