// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Gs1DigitalLinkToolkitTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CompressGs1DigitalLinkFeature : object, Xunit.IClassFixture<CompressGs1DigitalLinkFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "CompressGs1DigitalLink", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CompressGs1DigitalLink.feature"
#line hidden
        
        public CompressGs1DigitalLinkFeature(CompressGs1DigitalLinkFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Compress a decompressed Digital Link")]
        [Xunit.TraitAttribute("FeatureTitle", "CompressGs1DigitalLink")]
        [Xunit.TraitAttribute("Description", "Compress a decompressed Digital Link")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/00/998440410914660971", "https://id.gs1.org/AN2yxDhfaiaw", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013", "https://id.gs1.org/AQnYUc1gmg", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/10/ABC123", "https://id.gs1.org/AQnYUc1gmiCNV4JG", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/10/ABC123/21/72292641703", "https://id.gs1.org/AQnYUc1gmiCNV4JGQhcNT6K6c", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/22/AJY3095721P49/10/ABC123/21/72292641703", "https://id.gs1.org/AQnYUc1gmiCNV4JGQhcNT6K6cibQCWN9Pee9tT-PQ", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/22/AJY3095721P49/10/ABC123", "https://id.gs1.org/AQnYUc1gmiCNV4JGRNoBLG-nvPe2p_Ho", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/235/8TFV883a904GH%263", "https://id.gs1.org/AQnYUc1gmkax7ipGrOHDPC5YNI8hMz", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/21/72292641703", "https://id.gs1.org/AQnYUc1gmkIXDU-iun", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/22/AJY3095721P49/21/72292641703", "https://id.gs1.org/AQnYUc1gmkIXDU-iunIm0AljfT3nvbU_j0", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/22/AJY3095721P49", "https://id.gs1.org/AQnYUc1gmkTaASxvp7z3tqfx6", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/253/3060077601309", "https://id.gs1.org/JTLIetaiHYA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/255/5678409730535", "https://id.gs1.org/JVUqG5hJ5wA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/401/0541234537290A41%26GHpp33", "https://id.gs1.org/QBl2DVoxZM2jVm3ZOWEFoxTR5HDgzZg", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/402/21173492661712079", "https://id.gs1.org/QCJZyW9mC6Z4", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/410/5060917510004", "https://id.gs1.org/QQSaVjC_dA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/411/5060917510004", "https://id.gs1.org/QRSaVjC_dA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/412/5060917510004", "https://id.gs1.org/QSSaVjC_dA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/413/5060917510004", "https://id.gs1.org/QTSaVjC_dA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004", "https://id.gs1.org/QUSaVjC_dA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004/254/RP56J920471", "https://id.gs1.org/JUa0T-eifdtOO9UFEmlYwv3Q", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004/7040/5KFX", "https://id.gs1.org/QUSaVjC_dHBAVlCrg", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/415/5060917510004", "https://id.gs1.org/QVSaVjC_dA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/416/5060917510004", "https://id.gs1.org/QWSaVjC_dA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/417/5060917510004", "https://id.gs1.org/QXSaVjC_dA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/417/5060917510004/7040/5KFX", "https://id.gs1.org/QXSaVjC_dHBAVlCrg", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8004/0541234537290A41%26GHpp33/7040/7BVR", "https://id.gs1.org/cEB2CqjAAkuwatGLJm0as27JywgtGKaPI4cGbM", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49/10/ABC123/21/72292641" +
            "703", "https://id.gs1.org/EEarwSMhC4an0V05E2gEsb6e897an8ewAMGAkftmjYEy", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/10/ABC123/21/72292641703", "https://id.gs1.org/EEarwSMhC4an0V08ADBgJH7Zo2BMg", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49/10/ABC123", "https://id.gs1.org/EEarwSMibQCWN9Pee9tT-PYAGDASP2zRsCZ", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/10/ABC123", "https://id.gs1.org/EEarwSOABgwEj9s0bAmQ", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8003/04965031954585", "https://id.gs1.org/gAMJCAXukTMA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8004/0541234537290A41%26GHpp33", "https://id.gs1.org/gASXYNWjFkzaNWbdk5YQWjFNHkcODNm", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201", "https://id.gs1.org/gAYMBI_bNGwJk", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49", "https://id.gs1.org/Im0AljfT3nvbU_j2ABgwEj9s0bAmQ", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49/21/72292641703", "https://id.gs1.org/IQuGp9FdORNoBLG-nvPe2p_HsADBgJH7Zo2BMg", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/21/72292641703", "https://id.gs1.org/IQuGp9FdPAAwYCR-2aNgTI", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8010/0541234537290A41%23GH33/8011/6639047221", "https://id.gs1.org/gBCVYNWjFkzaNWbdk5YQWjFHHkM2cAI0xdvpGo", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8010/0541234537290A41%23GH33", "https://id.gs1.org/gBCVYNWjFkzaNWbdk5YQWjFHHkM2Y", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8013/5060917511473062B98T", "https://id.gs1.org/gBN05060917511473062B98T", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8017/817019610850151481", "https://id.gs1.org/gBe1ajAd9ATDk", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8017/817019610850151481/8019/4003812", "https://id.gs1.org/gBe1ajAd9ATDmAGXPRfk", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8018/411369833821910265", "https://id.gs1.org/gBhbV6rzBENPk", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8018/411369833821910265/8019/4003812", "https://id.gs1.org/gBhbV6rzBENPmAGXPRfk", new string[0])]
        public async System.Threading.Tasks.Task CompressADecompressedDigitalLink(string decompressedDigitalLink, string expectedDigitalLink, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("decompressedDigitalLink", decompressedDigitalLink);
            argumentsOfScenario.Add("expectedDigitalLink", expectedDigitalLink);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Compress a decompressed Digital Link", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await testRunner.GivenAsync(string.Format("I have a decompressed Digital Link \"{0}\"", decompressedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
    await testRunner.WhenAsync("I compress the decompressed Digital Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 8
    await testRunner.ThenAsync(string.Format("the compressed Digital Link should be \"{0}\"", expectedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Partially compress a decompressed Digital Link")]
        [Xunit.TraitAttribute("FeatureTitle", "CompressGs1DigitalLink")]
        [Xunit.TraitAttribute("Description", "Partially compress a decompressed Digital Link")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/00/998440410914660971", "https://id.gs1.org/00/998440410914660971", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013", "https://id.gs1.org/01/05412345000013", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/10/ABC123", "https://id.gs1.org/01/05412345000013/EEarwSM", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/10/ABC123/21/72292641703", "https://id.gs1.org/01/05412345000013/EEarwSMhC4an0V04", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/22/AJY3095721P49/10/ABC123/21/72292641703", "https://id.gs1.org/01/05412345000013/EEarwSMhC4an0V05E2gEsb6e897an8eg", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/22/AJY3095721P49/10/ABC123", "https://id.gs1.org/01/05412345000013/EEarwSMibQCWN9Pee9tT-PQ", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/235/8TFV883a904GH%263", "https://id.gs1.org/01/05412345000013/I1j3FSNWcOGeFywaR5CZm", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/22/AJY3095721P49", "https://id.gs1.org/01/05412345000013/Im0AljfT3nvbU_j0", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/21/72292641703", "https://id.gs1.org/01/05412345000013/IQuGp9FdO", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/22/AJY3095721P49/21/72292641703", "https://id.gs1.org/01/05412345000013/IQuGp9FdORNoBLG-nvPe2p_Ho", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/253/3060077601309", "https://id.gs1.org/253/3060077601309", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/255/5678409730535", "https://id.gs1.org/255/5678409730535", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/401/0541234537290A41%26GHpp33", "https://id.gs1.org/401/0541234537290A41%26GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/402/21173492661712079", "https://id.gs1.org/402/21173492661712079", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/410/5060917510004", "https://id.gs1.org/410/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/411/5060917510004", "https://id.gs1.org/411/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/412/5060917510004", "https://id.gs1.org/412/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/413/5060917510004", "https://id.gs1.org/413/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004", "https://id.gs1.org/414/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004/7040/5KFX", "https://id.gs1.org/414/5060917510004/cEBWUKu", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004/254/RP56J920471", "https://id.gs1.org/414/5060917510004/JUa0T-eifdtOO9Q", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/415/5060917510004", "https://id.gs1.org/415/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/416/5060917510004", "https://id.gs1.org/416/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/417/5060917510004", "https://id.gs1.org/417/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/417/5060917510004/7040/5KFX", "https://id.gs1.org/417/5060917510004/cEBWUKu", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8003/04965031954585", "https://id.gs1.org/8003/04965031954585", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8004/0541234537290A41%26GHpp33", "https://id.gs1.org/8004/0541234537290A41%26GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8004/0541234537290A41%26GHpp33/7040/7BVR", "https://id.gs1.org/8004/0541234537290A41%26GHpp33/cEB2Cqi", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201", "https://id.gs1.org/8006/054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/10/ABC123", "https://id.gs1.org/8006/054123450000130201/EEarwSM", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/10/ABC123/21/72292641703", "https://id.gs1.org/8006/054123450000130201/EEarwSMhC4an0V04", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49/10/ABC123/21/72292641" +
            "703", "https://id.gs1.org/8006/054123450000130201/EEarwSMhC4an0V05E2gEsb6e897an8eg", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49/10/ABC123", "https://id.gs1.org/8006/054123450000130201/EEarwSMibQCWN9Pee9tT-PQ", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49", "https://id.gs1.org/8006/054123450000130201/Im0AljfT3nvbU_j0", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/21/72292641703", "https://id.gs1.org/8006/054123450000130201/IQuGp9FdO", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49/21/72292641703", "https://id.gs1.org/8006/054123450000130201/IQuGp9FdORNoBLG-nvPe2p_Ho", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8010/0541234537290A41%23GH33", "https://id.gs1.org/8010/0541234537290A41%23GH33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8010/0541234537290A41%23GH33/8011/6639047221", "https://id.gs1.org/8010/0541234537290A41%23GH33/gBGmLt9I1", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8013/5060917511473062B98T", "https://id.gs1.org/8013/5060917511473062B98T", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8017/817019610850151481", "https://id.gs1.org/8017/817019610850151481", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8017/817019610850151481/8019/4003812", "https://id.gs1.org/8017/817019610850151481/gBlz0X5A", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8018/411369833821910265", "https://id.gs1.org/8018/411369833821910265", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8018/411369833821910265/8019/4003812", "https://id.gs1.org/8018/411369833821910265/gBlz0X5A", new string[0])]
        public async System.Threading.Tasks.Task PartiallyCompressADecompressedDigitalLink(string decompressedDigitalLink, string expectedDigitalLink, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("decompressedDigitalLink", decompressedDigitalLink);
            argumentsOfScenario.Add("expectedDigitalLink", expectedDigitalLink);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Partially compress a decompressed Digital Link", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 56
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 57
    await testRunner.GivenAsync(string.Format("I have a decompressed Digital Link \"{0}\"", decompressedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 58
    await testRunner.WhenAsync("I partially compress the decompressed Digital Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 59
    await testRunner.ThenAsync(string.Format("the compressed Digital Link should be \"{0}\"", expectedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Compress a decompressed Digital Link with short names")]
        [Xunit.TraitAttribute("FeatureTitle", "CompressGs1DigitalLink")]
        [Xunit.TraitAttribute("Description", "Compress a decompressed Digital Link with short names")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/sscc/998440410914660971", "https://id.gs1.org/AN2yxDhfaiaw", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013", "https://id.gs1.org/AQnYUc1gmg", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/lot/ABC123", "https://id.gs1.org/AQnYUc1gmiCNV4JG", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/lot/ABC123/ser/72292641703", "https://id.gs1.org/AQnYUc1gmiCNV4JGQhcNT6K6c", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/lot/ABC123/ser/722926417" +
            "03", "https://id.gs1.org/AQnYUc1gmiCNV4JGQhcNT6K6cibQCWN9Pee9tT-PQ", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/lot/ABC123", "https://id.gs1.org/AQnYUc1gmiCNV4JGRNoBLG-nvPe2p_Ho", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/235/8TFV883a904GH%263", "https://id.gs1.org/AQnYUc1gmkax7ipGrOHDPC5YNI8hMz", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/ser/72292641703", "https://id.gs1.org/AQnYUc1gmkIXDU-iun", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/ser/72292641703", "https://id.gs1.org/AQnYUc1gmkIXDU-iunIm0AljfT3nvbU_j0", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49", "https://id.gs1.org/AQnYUc1gmkTaASxvp7z3tqfx6", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gdti/3060077601309", "https://id.gs1.org/JTLIetaiHYA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gcn/5678409730535", "https://id.gs1.org/JVUqG5hJ5wA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/ginc/0541234537290A41%26GHpp33", "https://id.gs1.org/QBl2DVoxZM2jVm3ZOWEFoxTR5HDgzZg", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsin/21173492661712079", "https://id.gs1.org/QCJZyW9mC6Z4", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/shipTo/5060917510004", "https://id.gs1.org/QQSaVjC_dA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/billTo/5060917510004", "https://id.gs1.org/QRSaVjC_dA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/purchasedFrom/5060917510004", "https://id.gs1.org/QSSaVjC_dA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/shipFor/5060917510004", "https://id.gs1.org/QTSaVjC_dA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gln/5060917510004", "https://id.gs1.org/QUSaVjC_dA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gln/5060917510004/glnx/RP56J920471", "https://id.gs1.org/JUa0T-eifdtOO9UFEmlYwv3Q", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gln/5060917510004/7040/5KFX", "https://id.gs1.org/QUSaVjC_dHBAVlCrg", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/payTo/5060917510004", "https://id.gs1.org/QVSaVjC_dA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/glnProd/5060917510004", "https://id.gs1.org/QWSaVjC_dA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/party/5060917510004", "https://id.gs1.org/QXSaVjC_dA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/party/5060917510004/7040/5KFX", "https://id.gs1.org/QXSaVjC_dHBAVlCrg", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/grai/04965031954585", "https://id.gs1.org/gAMJCAXukTMA", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/giai/0541234537290A41%26GHpp33", "https://id.gs1.org/gASXYNWjFkzaNWbdk5YQWjFNHkcODNm", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/giai/0541234537290A41%26GHpp33/7040/7BVR", "https://id.gs1.org/cEB2CqjAAkuwatGLJm0as27JywgtGKaPI4cGbM", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/lot/ABC123/ser/72292" +
            "641703", "https://id.gs1.org/EEarwSMhC4an0V05E2gEsb6e897an8ewAMGAkftmjYEy", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/lot/ABC123/ser/72292641703", "https://id.gs1.org/EEarwSMhC4an0V08ADBgJH7Zo2BMg", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/lot/ABC123", "https://id.gs1.org/EEarwSMibQCWN9Pee9tT-PYAGDASP2zRsCZ", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/lot/ABC123", "https://id.gs1.org/EEarwSOABgwEj9s0bAmQ", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201", "https://id.gs1.org/gAYMBI_bNGwJk", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49", "https://id.gs1.org/Im0AljfT3nvbU_j2ABgwEj9s0bAmQ", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/ser/72292641703", "https://id.gs1.org/IQuGp9FdORNoBLG-nvPe2p_HsADBgJH7Zo2BMg", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/ser/72292641703", "https://id.gs1.org/IQuGp9FdPAAwYCR-2aNgTI", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/cpid/0541234537290A41%23GH33/cpsn/6639047221", "https://id.gs1.org/gBCVYNWjFkzaNWbdk5YQWjFHHkM2cAI0xdvpGo", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/cpid/0541234537290A41%23GH33", "https://id.gs1.org/gBCVYNWjFkzaNWbdk5YQWjFHHkM2Y", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gmn/5060917511473062B98T", "https://id.gs1.org/gBN05060917511473062B98T", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrnp/817019610850151481", "https://id.gs1.org/gBe1ajAd9ATDk", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrnp/817019610850151481/srin/4003812", "https://id.gs1.org/gBe1ajAd9ATDmAGXPRfk", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrn/411369833821910265", "https://id.gs1.org/gBhbV6rzBENPk", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrn/411369833821910265/srin/4003812", "https://id.gs1.org/gBhbV6rzBENPmAGXPRfk", new string[0])]
        public async System.Threading.Tasks.Task CompressADecompressedDigitalLinkWithShortNames(string decompressedDigitalLink, string expectedDigitalLink, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("decompressedDigitalLink", decompressedDigitalLink);
            argumentsOfScenario.Add("expectedDigitalLink", expectedDigitalLink);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Compress a decompressed Digital Link with short names", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 107
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 108
    await testRunner.GivenAsync(string.Format("I have a decompressed Digital Link \"{0}\"", decompressedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 109
    await testRunner.WhenAsync("I compress the decompressed Digital Link with short names", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 110
    await testRunner.ThenAsync(string.Format("the compressed Digital Link should be \"{0}\"", expectedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Partially compress a decompressed Digital Link with short names")]
        [Xunit.TraitAttribute("FeatureTitle", "CompressGs1DigitalLink")]
        [Xunit.TraitAttribute("Description", "Partially compress a decompressed Digital Link with short names")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/sscc/998440410914660971", "https://id.gs1.org/00/998440410914660971", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013", "https://id.gs1.org/01/05412345000013", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/lot/ABC123", "https://id.gs1.org/01/05412345000013/EEarwSM", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/lot/ABC123/ser/72292641703", "https://id.gs1.org/01/05412345000013/EEarwSMhC4an0V04", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/lot/ABC123/ser/722926417" +
            "03", "https://id.gs1.org/01/05412345000013/EEarwSMhC4an0V05E2gEsb6e897an8eg", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/lot/ABC123", "https://id.gs1.org/01/05412345000013/EEarwSMibQCWN9Pee9tT-PQ", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/235/8TFV883a904GH%263", "https://id.gs1.org/01/05412345000013/I1j3FSNWcOGeFywaR5CZm", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49", "https://id.gs1.org/01/05412345000013/Im0AljfT3nvbU_j0", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/ser/72292641703", "https://id.gs1.org/01/05412345000013/IQuGp9FdO", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/ser/72292641703", "https://id.gs1.org/01/05412345000013/IQuGp9FdORNoBLG-nvPe2p_Ho", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gdti/3060077601309", "https://id.gs1.org/253/3060077601309", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gcn/5678409730535", "https://id.gs1.org/255/5678409730535", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/ginc/0541234537290A41%26GHpp33", "https://id.gs1.org/401/0541234537290A41%26GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsin/21173492661712079", "https://id.gs1.org/402/21173492661712079", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/shipTo/5060917510004", "https://id.gs1.org/410/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/billTo/5060917510004", "https://id.gs1.org/411/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/purchasedFrom/5060917510004", "https://id.gs1.org/412/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/shipFor/5060917510004", "https://id.gs1.org/413/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gln/5060917510004", "https://id.gs1.org/414/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gln/5060917510004/7040/5KFX", "https://id.gs1.org/414/5060917510004/cEBWUKu", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gln/5060917510004/glnx/RP56J920471", "https://id.gs1.org/414/5060917510004/JUa0T-eifdtOO9Q", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/payTo/5060917510004", "https://id.gs1.org/415/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/glnProd/5060917510004", "https://id.gs1.org/416/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/party/5060917510004", "https://id.gs1.org/417/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/party/5060917510004/7040/5KFX", "https://id.gs1.org/417/5060917510004/cEBWUKu", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/grai/04965031954585", "https://id.gs1.org/8003/04965031954585", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/giai/0541234537290A41%26GHpp33", "https://id.gs1.org/8004/0541234537290A41%26GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/giai/0541234537290A41%26GHpp33/7040/7BVR", "https://id.gs1.org/8004/0541234537290A41%26GHpp33/cEB2Cqi", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201", "https://id.gs1.org/8006/054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/lot/ABC123", "https://id.gs1.org/8006/054123450000130201/EEarwSM", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/lot/ABC123/ser/72292641703", "https://id.gs1.org/8006/054123450000130201/EEarwSMhC4an0V04", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/lot/ABC123/ser/72292" +
            "641703", "https://id.gs1.org/8006/054123450000130201/EEarwSMhC4an0V05E2gEsb6e897an8eg", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/lot/ABC123", "https://id.gs1.org/8006/054123450000130201/EEarwSMibQCWN9Pee9tT-PQ", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49", "https://id.gs1.org/8006/054123450000130201/Im0AljfT3nvbU_j0", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/ser/72292641703", "https://id.gs1.org/8006/054123450000130201/IQuGp9FdO", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/ser/72292641703", "https://id.gs1.org/8006/054123450000130201/IQuGp9FdORNoBLG-nvPe2p_Ho", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/cpid/0541234537290A41%23GH33", "https://id.gs1.org/8010/0541234537290A41%23GH33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/cpid/0541234537290A41%23GH33/cpsn/6639047221", "https://id.gs1.org/8010/0541234537290A41%23GH33/gBGmLt9I1", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gmn/5060917511473062B98T", "https://id.gs1.org/8013/5060917511473062B98T", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrnp/817019610850151481", "https://id.gs1.org/8017/817019610850151481", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrnp/817019610850151481/srin/4003812", "https://id.gs1.org/8017/817019610850151481/gBlz0X5A", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrn/411369833821910265", "https://id.gs1.org/8018/411369833821910265", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrn/411369833821910265/srin/4003812", "https://id.gs1.org/8018/411369833821910265/gBlz0X5A", new string[0])]
        public async System.Threading.Tasks.Task PartiallyCompressADecompressedDigitalLinkWithShortNames(string decompressedDigitalLink, string expectedDigitalLink, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("decompressedDigitalLink", decompressedDigitalLink);
            argumentsOfScenario.Add("expectedDigitalLink", expectedDigitalLink);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Partially compress a decompressed Digital Link with short names", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 158
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 159
    await testRunner.GivenAsync(string.Format("I have a decompressed Digital Link \"{0}\"", decompressedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 160
    await testRunner.WhenAsync("I partially compress the decompressed Digital Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 161
    await testRunner.ThenAsync(string.Format("the compressed Digital Link should be \"{0}\"", expectedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Partially compress decompressed Digital Link with short names to a Digital Link w" +
            "ith short names")]
        [Xunit.TraitAttribute("FeatureTitle", "CompressGs1DigitalLink")]
        [Xunit.TraitAttribute("Description", "Partially compress decompressed Digital Link with short names to a Digital Link w" +
            "ith short names")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/sscc/998440410914660971", "https://id.gs1.org/sscc/998440410914660971", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013", "https://id.gs1.org/gtin/05412345000013", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/lot/ABC123", "https://id.gs1.org/gtin/05412345000013/EEarwSM", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/lot/ABC123/ser/72292641703", "https://id.gs1.org/gtin/05412345000013/EEarwSMhC4an0V04", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/lot/ABC123/ser/722926417" +
            "03", "https://id.gs1.org/gtin/05412345000013/EEarwSMhC4an0V05E2gEsb6e897an8eg", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/lot/ABC123", "https://id.gs1.org/gtin/05412345000013/EEarwSMibQCWN9Pee9tT-PQ", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/235/8TFV883a904GH%263", "https://id.gs1.org/gtin/05412345000013/I1j3FSNWcOGeFywaR5CZm", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49", "https://id.gs1.org/gtin/05412345000013/Im0AljfT3nvbU_j0", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/ser/72292641703", "https://id.gs1.org/gtin/05412345000013/IQuGp9FdO", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/ser/72292641703", "https://id.gs1.org/gtin/05412345000013/IQuGp9FdORNoBLG-nvPe2p_Ho", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gdti/3060077601309", "https://id.gs1.org/gdti/3060077601309", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gcn/5678409730535", "https://id.gs1.org/gcn/5678409730535", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/ginc/0541234537290A41%26GHpp33", "https://id.gs1.org/ginc/0541234537290A41%26GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsin/21173492661712079", "https://id.gs1.org/gsin/21173492661712079", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/shipTo/5060917510004", "https://id.gs1.org/shipTo/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/billTo/5060917510004", "https://id.gs1.org/billTo/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/purchasedFrom/5060917510004", "https://id.gs1.org/purchasedFrom/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/shipFor/5060917510004", "https://id.gs1.org/shipFor/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gln/5060917510004", "https://id.gs1.org/gln/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gln/5060917510004/7040/5KFX", "https://id.gs1.org/gln/5060917510004/cEBWUKu", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gln/5060917510004/glnx/RP56J920471", "https://id.gs1.org/gln/5060917510004/JUa0T-eifdtOO9Q", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/payTo/5060917510004", "https://id.gs1.org/payTo/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/glnProd/5060917510004", "https://id.gs1.org/glnProd/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/party/5060917510004", "https://id.gs1.org/party/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/party/5060917510004/7040/5KFX", "https://id.gs1.org/party/5060917510004/cEBWUKu", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/grai/04965031954585", "https://id.gs1.org/grai/04965031954585", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/giai/0541234537290A41%26GHpp33", "https://id.gs1.org/giai/0541234537290A41%26GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/giai/0541234537290A41%26GHpp33/7040/7BVR", "https://id.gs1.org/giai/0541234537290A41%26GHpp33/cEB2Cqi", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201", "https://id.gs1.org/itip/054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/lot/ABC123", "https://id.gs1.org/itip/054123450000130201/EEarwSM", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/lot/ABC123/ser/72292641703", "https://id.gs1.org/itip/054123450000130201/EEarwSMhC4an0V04", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/lot/ABC123/ser/72292" +
            "641703", "https://id.gs1.org/itip/054123450000130201/EEarwSMhC4an0V05E2gEsb6e897an8eg", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/lot/ABC123", "https://id.gs1.org/itip/054123450000130201/EEarwSMibQCWN9Pee9tT-PQ", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49", "https://id.gs1.org/itip/054123450000130201/Im0AljfT3nvbU_j0", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/ser/72292641703", "https://id.gs1.org/itip/054123450000130201/IQuGp9FdO", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/ser/72292641703", "https://id.gs1.org/itip/054123450000130201/IQuGp9FdORNoBLG-nvPe2p_Ho", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/cpid/0541234537290A41%23GH33", "https://id.gs1.org/cpid/0541234537290A41%23GH33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/cpid/0541234537290A41%23GH33/cpsn/6639047221", "https://id.gs1.org/cpid/0541234537290A41%23GH33/gBGmLt9I1", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gmn/5060917511473062B98T", "https://id.gs1.org/gmn/5060917511473062B98T", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrnp/817019610850151481", "https://id.gs1.org/gsrnp/817019610850151481", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrnp/817019610850151481/srin/4003812", "https://id.gs1.org/gsrnp/817019610850151481/gBlz0X5A", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrn/411369833821910265", "https://id.gs1.org/gsrn/411369833821910265", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrn/411369833821910265/srin/4003812", "https://id.gs1.org/gsrn/411369833821910265/gBlz0X5A", new string[0])]
        public async System.Threading.Tasks.Task PartiallyCompressDecompressedDigitalLinkWithShortNamesToADigitalLinkWithShortNames(string decompressedDigitalLink, string expectedDigitalLink, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("decompressedDigitalLink", decompressedDigitalLink);
            argumentsOfScenario.Add("expectedDigitalLink", expectedDigitalLink);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Partially compress decompressed Digital Link with short names to a Digital Link w" +
                    "ith short names", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 209
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 210
    await testRunner.GivenAsync(string.Format("I have a decompressed Digital Link \"{0}\"", decompressedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 211
    await testRunner.WhenAsync("I partially compress the decompressed Digital Link to a Digital Link with short n" +
                        "ames", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 212
    await testRunner.ThenAsync(string.Format("the compressed Digital Link should be \"{0}\"", expectedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CompressGs1DigitalLinkFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CompressGs1DigitalLinkFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
