// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Gs1DigitalLinkToolkitTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class DecompressGs1DigitalLinkFeature : object, Xunit.IClassFixture<DecompressGs1DigitalLinkFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "DecompressGs1DigitalLink", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "DecompressGs1DigitalLink.feature"
#line hidden
        
        public DecompressGs1DigitalLinkFeature(DecompressGs1DigitalLinkFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Decompress a compressed Digital Link")]
        [Xunit.TraitAttribute("FeatureTitle", "DecompressGs1DigitalLink")]
        [Xunit.TraitAttribute("Description", "Decompress a compressed Digital Link")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/I1j3FSNWcOGeFywaR5CZmSmWQ9a1EOwA", "https://id.gs1.org/253/3060077601309", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AN2yxDhfaiaw", "https://id.gs1.org/00/998440410914660971", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmg", "https://id.gs1.org/01/05412345000013", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmiCNV4JG", "https://id.gs1.org/01/05412345000013/10/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmiCNV4JGQhcNT6K6c", "https://id.gs1.org/01/05412345000013/10/ABC123/21/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmiCNV4JGQhcNT6K6cibQCWN9Pee9tT-PQ", "https://id.gs1.org/01/05412345000013/22/AJY3095721P49/10/ABC123/21/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmiCNV4JGRNoBLG-nvPe2p_Ho", "https://id.gs1.org/01/05412345000013/22/AJY3095721P49/10/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmkax7ipGrOHDPC5YNI8hMz", "https://id.gs1.org/01/05412345000013/235/8TFV883a904GH%263", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmkIXDU-iun", "https://id.gs1.org/01/05412345000013/21/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmkIXDU-iunIm0AljfT3nvbU_j0", "https://id.gs1.org/01/05412345000013/22/AJY3095721P49/21/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmkTaASxvp7z3tqfx6", "https://id.gs1.org/01/05412345000013/22/AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/JTLIetaiHYA", "https://id.gs1.org/253/3060077601309", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/JVUqG5hJ5wA", "https://id.gs1.org/255/5678409730535", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QBl2DVoxZM2jVm3ZOWEFoxTR5HDgzZg", "https://id.gs1.org/401/0541234537290A41%26GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QCJZyW9mC6Z4", "https://id.gs1.org/402/21173492661712079", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QQSaVjC_dA", "https://id.gs1.org/410/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QRSaVjC_dA", "https://id.gs1.org/411/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QSSaVjC_dA", "https://id.gs1.org/412/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QTSaVjC_dA", "https://id.gs1.org/413/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QUSaVjC_dA", "https://id.gs1.org/414/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/JUa0T-eifdtOO9UFEmlYwv3Q", "https://id.gs1.org/414/5060917510004/254/RP56J920471", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QUSaVjC_dHBAVlCrg", "https://id.gs1.org/414/5060917510004/7040/5KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QVSaVjC_dA", "https://id.gs1.org/415/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QWSaVjC_dA", "https://id.gs1.org/416/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QXSaVjC_dA", "https://id.gs1.org/417/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QXSaVjC_dHBAVlCrg", "https://id.gs1.org/417/5060917510004/7040/5KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/cEB2CqjAAkuwatGLJm0as27JywgtGKaPI4cGbM", "https://id.gs1.org/8004/0541234537290A41%26GHpp33/7040/7BVR", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/EEarwSMhC4an0V05E2gEsb6e897an8ewAMGAkftmjYEy", "https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49/10/ABC123/21/72292641" +
            "703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/EEarwSMhC4an0V08ADBgJH7Zo2BMg", "https://id.gs1.org/8006/054123450000130201/10/ABC123/21/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/EEarwSMibQCWN9Pee9tT-PYAGDASP2zRsCZ", "https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49/10/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/EEarwSOABgwEj9s0bAmQ", "https://id.gs1.org/8006/054123450000130201/10/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gAMJCAXukTMA", "https://id.gs1.org/8003/04965031954585", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gASXYNWjFkzaNWbdk5YQWjFNHkcODNm", "https://id.gs1.org/8004/0541234537290A41%26GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gAYMBI_bNGwJk", "https://id.gs1.org/8006/054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/Im0AljfT3nvbU_j2ABgwEj9s0bAmQ", "https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/IQuGp9FdORNoBLG-nvPe2p_HsADBgJH7Zo2BMg", "https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49/21/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/IQuGp9FdPAAwYCR-2aNgTI", "https://id.gs1.org/8006/054123450000130201/21/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBCVYNWjFkzaNWbdk5YQWjFHHkM2cAI0xdvpGo", "https://id.gs1.org/8010/0541234537290A41%23GH33/8011/6639047221", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBCVYNWjFkzaNWbdk5YQWjFHHkM2Y", "https://id.gs1.org/8010/0541234537290A41%23GH33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBN05060917511473062B98T", "https://id.gs1.org/8013/5060917511473062B98T", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBe1ajAd9ATDk", "https://id.gs1.org/8017/817019610850151481", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBe1ajAd9ATDmAGXPRfk", "https://id.gs1.org/8017/817019610850151481/8019/4003812", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBhbV6rzBENPk", "https://id.gs1.org/8018/411369833821910265", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBhbV6rzBENPmAGXPRfk", "https://id.gs1.org/8018/411369833821910265/8019/4003812", new string[0])]
        public async System.Threading.Tasks.Task DecompressACompressedDigitalLink(string compressedDigitalLink, string expectedDigitalLink, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("compressedDigitalLink", compressedDigitalLink);
            argumentsOfScenario.Add("expectedDigitalLink", expectedDigitalLink);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Decompress a compressed Digital Link", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await testRunner.GivenAsync(string.Format("I have a compressed Digital Link \"{0}\"", compressedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
    await testRunner.WhenAsync("I decompress the compressed Digital Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 8
    await testRunner.ThenAsync(string.Format("the decompressed Digital Link should be \"{0}\"", expectedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Decompress a partially compressed Digital Link")]
        [Xunit.TraitAttribute("FeatureTitle", "DecompressGs1DigitalLink")]
        [Xunit.TraitAttribute("Description", "Decompress a partially compressed Digital Link")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/00/998440410914660971", "https://id.gs1.org/00/998440410914660971", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013", "https://id.gs1.org/01/05412345000013", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/EEarwSM", "https://id.gs1.org/01/05412345000013/10/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/EEarwSMhC4an0V04", "https://id.gs1.org/01/05412345000013/10/ABC123/21/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/EEarwSMhC4an0V05E2gEsb6e897an8eg", "https://id.gs1.org/01/05412345000013/22/AJY3095721P49/10/ABC123/21/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/EEarwSMibQCWN9Pee9tT-PQ", "https://id.gs1.org/01/05412345000013/22/AJY3095721P49/10/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/I1j3FSNWcOGeFywaR5CZm", "https://id.gs1.org/01/05412345000013/235/8TFV883a904GH%263", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/Im0AljfT3nvbU_j0", "https://id.gs1.org/01/05412345000013/22/AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/IQuGp9FdO", "https://id.gs1.org/01/05412345000013/21/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/IQuGp9FdORNoBLG-nvPe2p_Ho", "https://id.gs1.org/01/05412345000013/22/AJY3095721P49/21/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/5412345000013/IQuGp9FdORNoBLG-nvPe2p_Ho", "https://id.gs1.org/01/05412345000013/22/AJY3095721P49/21/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/253/3060077601309", "https://id.gs1.org/253/3060077601309", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/255/5678409730535", "https://id.gs1.org/255/5678409730535", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/401/0541234537290A41%26GHpp33", "https://id.gs1.org/401/0541234537290A41%26GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/402/21173492661712079", "https://id.gs1.org/402/21173492661712079", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/410/5060917510004", "https://id.gs1.org/410/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/411/5060917510004", "https://id.gs1.org/411/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/412/5060917510004", "https://id.gs1.org/412/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/413/5060917510004", "https://id.gs1.org/413/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004", "https://id.gs1.org/414/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004/cEBWUKu", "https://id.gs1.org/414/5060917510004/7040/5KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004/JUa0T-eifdtOO9Q", "https://id.gs1.org/414/5060917510004/254/RP56J920471", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/415/5060917510004", "https://id.gs1.org/415/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/416/5060917510004", "https://id.gs1.org/416/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/417/5060917510004", "https://id.gs1.org/417/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/417/5060917510004/cEBWUKu", "https://id.gs1.org/417/5060917510004/7040/5KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8003/04965031954585", "https://id.gs1.org/8003/04965031954585", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8004/0541234537290A41%26GHpp33", "https://id.gs1.org/8004/0541234537290A41%26GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8004/0541234537290A41%26GHpp33/cEB2Cqi", "https://id.gs1.org/8004/0541234537290A41%26GHpp33/7040/7BVR", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201", "https://id.gs1.org/8006/054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/EEarwSM", "https://id.gs1.org/8006/054123450000130201/10/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/EEarwSMhC4an0V04", "https://id.gs1.org/8006/054123450000130201/10/ABC123/21/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/EEarwSMhC4an0V05E2gEsb6e897an8eg", "https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49/10/ABC123/21/72292641" +
            "703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/EEarwSMibQCWN9Pee9tT-PQ", "https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49/10/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/Im0AljfT3nvbU_j0", "https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/IQuGp9FdO", "https://id.gs1.org/8006/054123450000130201/21/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/IQuGp9FdORNoBLG-nvPe2p_Ho", "https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49/21/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8010/0541234537290A41%23GH33", "https://id.gs1.org/8010/0541234537290A41%23GH33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8010/0541234537290A41%23GH33/gBGmLt9I1", "https://id.gs1.org/8010/0541234537290A41%23GH33/8011/6639047221", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8013/5060917511473062B98T", "https://id.gs1.org/8013/5060917511473062B98T", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8017/817019610850151481", "https://id.gs1.org/8017/817019610850151481", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8017/817019610850151481/gBlz0X5A", "https://id.gs1.org/8017/817019610850151481/8019/4003812", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8018/411369833821910265", "https://id.gs1.org/8018/411369833821910265", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8018/411369833821910265/gBlz0X5A", "https://id.gs1.org/8018/411369833821910265/8019/4003812", new string[0])]
        public async System.Threading.Tasks.Task DecompressAPartiallyCompressedDigitalLink(string partiallyCompressedDigitalLink, string expectedDigitalLink, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("partiallyCompressedDigitalLink", partiallyCompressedDigitalLink);
            argumentsOfScenario.Add("expectedDigitalLink", expectedDigitalLink);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Decompress a partially compressed Digital Link", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 57
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 58
    await testRunner.GivenAsync(string.Format("I have a partially compressed Digital Link \"{0}\"", partiallyCompressedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 59
    await testRunner.WhenAsync("I decompress the compressed Digital Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 60
    await testRunner.ThenAsync(string.Format("the decompressed Digital Link should be \"{0}\"", expectedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Decompress a compressed Digital Link to a Digital Link with short names")]
        [Xunit.TraitAttribute("FeatureTitle", "DecompressGs1DigitalLink")]
        [Xunit.TraitAttribute("Description", "Decompress a compressed Digital Link to a Digital Link with short names")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AN2yxDhfaiaw", "https://id.gs1.org/sscc/998440410914660971", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmg", "https://id.gs1.org/gtin/05412345000013", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmiCNV4JG", "https://id.gs1.org/gtin/05412345000013/lot/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmiCNV4JGQhcNT6K6c", "https://id.gs1.org/gtin/05412345000013/lot/ABC123/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmiCNV4JGQhcNT6K6cibQCWN9Pee9tT-PQ", "https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/lot/ABC123/ser/722926417" +
            "03", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmiCNV4JGRNoBLG-nvPe2p_Ho", "https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/lot/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmkax7ipGrOHDPC5YNI8hMz", "https://id.gs1.org/gtin/05412345000013/235/8TFV883a904GH%263", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmkIXDU-iun", "https://id.gs1.org/gtin/05412345000013/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmkIXDU-iunIm0AljfT3nvbU_j0", "https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmkTaASxvp7z3tqfx6", "https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/JTLIetaiHYA", "https://id.gs1.org/gdti/3060077601309", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/JVUqG5hJ5wA", "https://id.gs1.org/gcn/5678409730535", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QBl2DVoxZM2jVm3ZOWEFoxTR5HDgzZg", "https://id.gs1.org/ginc/0541234537290A41%26GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QCJZyW9mC6Z4", "https://id.gs1.org/gsin/21173492661712079", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QQSaVjC_dA", "https://id.gs1.org/shipTo/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QRSaVjC_dA", "https://id.gs1.org/billTo/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QSSaVjC_dA", "https://id.gs1.org/purchasedFrom/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QTSaVjC_dA", "https://id.gs1.org/shipFor/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QUSaVjC_dA", "https://id.gs1.org/gln/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/JUa0T-eifdtOO9UFEmlYwv3Q", "https://id.gs1.org/gln/5060917510004/glnx/RP56J920471", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QUSaVjC_dHBAVlCrg", "https://id.gs1.org/gln/5060917510004/7040/5KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QVSaVjC_dA", "https://id.gs1.org/payTo/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QWSaVjC_dA", "https://id.gs1.org/glnProd/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QXSaVjC_dA", "https://id.gs1.org/party/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QXSaVjC_dHBAVlCrg", "https://id.gs1.org/party/5060917510004/7040/5KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gAMJCAXukTMA", "https://id.gs1.org/grai/04965031954585", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gASXYNWjFkzaNWbdk5YQWjFNHkcODNm", "https://id.gs1.org/giai/0541234537290A41%26GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/cEB2CqjAAkuwatGLJm0as27JywgtGKaPI4cGbM", "https://id.gs1.org/giai/0541234537290A41%26GHpp33/7040/7BVR", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/EEarwSMhC4an0V05E2gEsb6e897an8ewAMGAkftmjYEy", "https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/lot/ABC123/ser/72292" +
            "641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/EEarwSMhC4an0V08ADBgJH7Zo2BMg", "https://id.gs1.org/itip/054123450000130201/lot/ABC123/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/EEarwSMibQCWN9Pee9tT-PYAGDASP2zRsCZ", "https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/lot/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/EEarwSOABgwEj9s0bAmQ", "https://id.gs1.org/itip/054123450000130201/lot/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gAYMBI_bNGwJk", "https://id.gs1.org/itip/054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/Im0AljfT3nvbU_j2ABgwEj9s0bAmQ", "https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/IQuGp9FdORNoBLG-nvPe2p_HsADBgJH7Zo2BMg", "https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/IQuGp9FdPAAwYCR-2aNgTI", "https://id.gs1.org/itip/054123450000130201/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBCVYNWjFkzaNWbdk5YQWjFHHkM2cAI0xdvpGo", "https://id.gs1.org/cpid/0541234537290A41%23GH33/cpsn/6639047221", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBCVYNWjFkzaNWbdk5YQWjFHHkM2Y", "https://id.gs1.org/cpid/0541234537290A41%23GH33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBN05060917511473062B98T", "https://id.gs1.org/gmn/5060917511473062B98T", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBe1ajAd9ATDk", "https://id.gs1.org/gsrnp/817019610850151481", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBe1ajAd9ATDmAGXPRfk", "https://id.gs1.org/gsrnp/817019610850151481/srin/4003812", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBhbV6rzBENPk", "https://id.gs1.org/gsrn/411369833821910265", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBhbV6rzBENPmAGXPRfk", "https://id.gs1.org/gsrn/411369833821910265/srin/4003812", new string[0])]
        public async System.Threading.Tasks.Task DecompressACompressedDigitalLinkToADigitalLinkWithShortNames(string compressedDigitalLink, string expectedDigitalLink, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("compressedDigitalLink", compressedDigitalLink);
            argumentsOfScenario.Add("expectedDigitalLink", expectedDigitalLink);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Decompress a compressed Digital Link to a Digital Link with short names", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 109
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 110
    await testRunner.GivenAsync(string.Format("I have a compressed Digital Link \"{0}\"", compressedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 111
    await testRunner.WhenAsync("I decompress the compressed Digital Link to a Digital Link with short names", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 112
    await testRunner.ThenAsync(string.Format("the decompressed Digital Link should be \"{0}\"", expectedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Decompress a partially compressed Digital Link with AIs to a Digital Link with sh" +
            "ort names")]
        [Xunit.TraitAttribute("FeatureTitle", "DecompressGs1DigitalLink")]
        [Xunit.TraitAttribute("Description", "Decompress a partially compressed Digital Link with AIs to a Digital Link with sh" +
            "ort names")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/00/998440410914660971", "https://id.gs1.org/sscc/998440410914660971", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013", "https://id.gs1.org/gtin/05412345000013", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/EEarwSM", "https://id.gs1.org/gtin/05412345000013/lot/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/EEarwSMhC4an0V04", "https://id.gs1.org/gtin/05412345000013/lot/ABC123/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/EEarwSMhC4an0V05E2gEsb6e897an8eg", "https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/lot/ABC123/ser/722926417" +
            "03", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/EEarwSMibQCWN9Pee9tT-PQ", "https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/lot/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/I1j3FSNWcOGeFywaR5CZm", "https://id.gs1.org/gtin/05412345000013/235/8TFV883a904GH%263", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/Im0AljfT3nvbU_j0", "https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/IQuGp9FdO", "https://id.gs1.org/gtin/05412345000013/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/IQuGp9FdORNoBLG-nvPe2p_Ho", "https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/5412345000013/IQuGp9FdORNoBLG-nvPe2p_Ho", "https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/253/3060077601309", "https://id.gs1.org/gdti/3060077601309", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/255/5678409730535", "https://id.gs1.org/gcn/5678409730535", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/401/0541234537290A41%26GHpp33", "https://id.gs1.org/ginc/0541234537290A41%26GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/402/21173492661712079", "https://id.gs1.org/gsin/21173492661712079", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/410/5060917510004", "https://id.gs1.org/shipTo/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/411/5060917510004", "https://id.gs1.org/billTo/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/412/5060917510004", "https://id.gs1.org/purchasedFrom/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/413/5060917510004", "https://id.gs1.org/shipFor/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004", "https://id.gs1.org/gln/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004/cEBWUKu", "https://id.gs1.org/gln/5060917510004/7040/5KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004/JUa0T-eifdtOO9Q", "https://id.gs1.org/gln/5060917510004/glnx/RP56J920471", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/415/5060917510004", "https://id.gs1.org/payTo/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/416/5060917510004", "https://id.gs1.org/glnProd/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/417/5060917510004", "https://id.gs1.org/party/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/417/5060917510004/cEBWUKu", "https://id.gs1.org/party/5060917510004/7040/5KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8003/04965031954585", "https://id.gs1.org/grai/04965031954585", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8004/0541234537290A41%26GHpp33", "https://id.gs1.org/giai/0541234537290A41%26GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8004/0541234537290A41%26GHpp33/cEB2Cqi", "https://id.gs1.org/giai/0541234537290A41%26GHpp33/7040/7BVR", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201", "https://id.gs1.org/itip/054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/EEarwSM", "https://id.gs1.org/itip/054123450000130201/lot/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/EEarwSMhC4an0V04", "https://id.gs1.org/itip/054123450000130201/lot/ABC123/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/EEarwSMhC4an0V05E2gEsb6e897an8eg", "https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/lot/ABC123/ser/72292" +
            "641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/EEarwSMibQCWN9Pee9tT-PQ", "https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/lot/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/Im0AljfT3nvbU_j0", "https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/IQuGp9FdO", "https://id.gs1.org/itip/054123450000130201/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/IQuGp9FdORNoBLG-nvPe2p_Ho", "https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8010/0541234537290A41%23GH33", "https://id.gs1.org/cpid/0541234537290A41%23GH33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8010/0541234537290A41%23GH33/gBGmLt9I1", "https://id.gs1.org/cpid/0541234537290A41%23GH33/cpsn/6639047221", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8013/5060917511473062B98T", "https://id.gs1.org/gmn/5060917511473062B98T", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8017/817019610850151481", "https://id.gs1.org/gsrnp/817019610850151481", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8017/817019610850151481/gBlz0X5A", "https://id.gs1.org/gsrnp/817019610850151481/srin/4003812", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8018/411369833821910265", "https://id.gs1.org/gsrn/411369833821910265", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8018/411369833821910265/gBlz0X5A", "https://id.gs1.org/gsrn/411369833821910265/srin/4003812", new string[0])]
        public async System.Threading.Tasks.Task DecompressAPartiallyCompressedDigitalLinkWithAIsToADigitalLinkWithShortNames(string partiallyCompressedDigitalLink, string expectedDigitalLink, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("partiallyCompressedDigitalLink", partiallyCompressedDigitalLink);
            argumentsOfScenario.Add("expectedDigitalLink", expectedDigitalLink);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Decompress a partially compressed Digital Link with AIs to a Digital Link with sh" +
                    "ort names", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 160
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 161
    await testRunner.GivenAsync(string.Format("I have a partially compressed Digital Link \"{0}\"", partiallyCompressedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 162
    await testRunner.WhenAsync("I decompress the compressed Digital Link to a Digital Link with short names", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 163
    await testRunner.ThenAsync(string.Format("the decompressed Digital Link should be \"{0}\"", expectedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Decompress a partially compressed Digital Link with short names to a Digital Link" +
            " with short names")]
        [Xunit.TraitAttribute("FeatureTitle", "DecompressGs1DigitalLink")]
        [Xunit.TraitAttribute("Description", "Decompress a partially compressed Digital Link with short names to a Digital Link" +
            " with short names")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/sscc/998440410914660971", "https://id.gs1.org/sscc/998440410914660971", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013", "https://id.gs1.org/gtin/05412345000013", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/EEarwSM", "https://id.gs1.org/gtin/05412345000013/lot/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/EEarwSMhC4an0V04", "https://id.gs1.org/gtin/05412345000013/lot/ABC123/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/EEarwSMhC4an0V05E2gEsb6e897an8eg", "https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/lot/ABC123/ser/722926417" +
            "03", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/EEarwSMibQCWN9Pee9tT-PQ", "https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/lot/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/I1j3FSNWcOGeFywaR5CZm", "https://id.gs1.org/gtin/05412345000013/235/8TFV883a904GH%263", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/Im0AljfT3nvbU_j0", "https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/IQuGp9FdO", "https://id.gs1.org/gtin/05412345000013/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/IQuGp9FdORNoBLG-nvPe2p_Ho", "https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/5412345000013/IQuGp9FdORNoBLG-nvPe2p_Ho", "https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gdti/3060077601309", "https://id.gs1.org/gdti/3060077601309", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gcn/5678409730535", "https://id.gs1.org/gcn/5678409730535", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/ginc/0541234537290A41%26GHpp33", "https://id.gs1.org/ginc/0541234537290A41%26GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsin/21173492661712079", "https://id.gs1.org/gsin/21173492661712079", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/shipTo/5060917510004", "https://id.gs1.org/shipTo/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/billTo/5060917510004", "https://id.gs1.org/billTo/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/purchasedFrom/5060917510004", "https://id.gs1.org/purchasedFrom/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/shipFor/5060917510004", "https://id.gs1.org/shipFor/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gln/5060917510004", "https://id.gs1.org/gln/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gln/5060917510004/cEBWUKu", "https://id.gs1.org/gln/5060917510004/7040/5KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gln/5060917510004/JUa0T-eifdtOO9Q", "https://id.gs1.org/gln/5060917510004/glnx/RP56J920471", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/payTo/5060917510004", "https://id.gs1.org/payTo/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/glnProd/5060917510004", "https://id.gs1.org/glnProd/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/party/5060917510004", "https://id.gs1.org/party/5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/party/5060917510004/cEBWUKu", "https://id.gs1.org/party/5060917510004/7040/5KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/grai/04965031954585", "https://id.gs1.org/grai/04965031954585", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/giai/0541234537290A41%26GHpp33", "https://id.gs1.org/giai/0541234537290A41%26GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/giai/0541234537290A41%26GHpp33/cEB2Cqi", "https://id.gs1.org/giai/0541234537290A41%26GHpp33/7040/7BVR", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201", "https://id.gs1.org/itip/054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/EEarwSM", "https://id.gs1.org/itip/054123450000130201/lot/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/EEarwSMhC4an0V04", "https://id.gs1.org/itip/054123450000130201/lot/ABC123/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/EEarwSMhC4an0V05E2gEsb6e897an8eg", "https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/lot/ABC123/ser/72292" +
            "641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/EEarwSMibQCWN9Pee9tT-PQ", "https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/lot/ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/Im0AljfT3nvbU_j0", "https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/IQuGp9FdO", "https://id.gs1.org/itip/054123450000130201/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/IQuGp9FdORNoBLG-nvPe2p_Ho", "https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/ser/72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/cpid/0541234537290A41%23GH33", "https://id.gs1.org/cpid/0541234537290A41%23GH33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/cpid/0541234537290A41%23GH33/gBGmLt9I1", "https://id.gs1.org/cpid/0541234537290A41%23GH33/cpsn/6639047221", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gmn/5060917511473062B98T", "https://id.gs1.org/gmn/5060917511473062B98T", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrnp/817019610850151481", "https://id.gs1.org/gsrnp/817019610850151481", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrnp/817019610850151481/gBlz0X5A", "https://id.gs1.org/gsrnp/817019610850151481/srin/4003812", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrn/411369833821910265", "https://id.gs1.org/gsrn/411369833821910265", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrn/411369833821910265/gBlz0X5A", "https://id.gs1.org/gsrn/411369833821910265/srin/4003812", new string[0])]
        public async System.Threading.Tasks.Task DecompressAPartiallyCompressedDigitalLinkWithShortNamesToADigitalLinkWithShortNames(string partiallyCompressedDigitalLink, string expectedDigitalLink, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("partiallyCompressedDigitalLink", partiallyCompressedDigitalLink);
            argumentsOfScenario.Add("expectedDigitalLink", expectedDigitalLink);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Decompress a partially compressed Digital Link with short names to a Digital Link" +
                    " with short names", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 212
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 213
    await testRunner.GivenAsync(string.Format("I have a partially compressed Digital Link \"{0}\"", partiallyCompressedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 214
    await testRunner.WhenAsync("I decompress the compressed Digital Link to a Digital Link with short names", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 215
    await testRunner.ThenAsync(string.Format("the decompressed Digital Link should be \"{0}\"", expectedDigitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await DecompressGs1DigitalLinkFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await DecompressGs1DigitalLinkFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
