// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Gs1DigitalLinkToolkitTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Gs1CompressedDigitalLinkToGs1ElementStringsFeature : object, Xunit.IClassFixture<Gs1CompressedDigitalLinkToGs1ElementStringsFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Gs1CompressedDigitalLinkToGs1ElementStrings", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Gs1CompressedDigitalLinkToGs1ElementStrings.feature"
#line hidden
        
        public Gs1CompressedDigitalLinkToGs1ElementStringsFeature(Gs1CompressedDigitalLinkToGs1ElementStringsFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Convert an uncompressed Digital Link to an element string")]
        [Xunit.TraitAttribute("FeatureTitle", "Gs1CompressedDigitalLinkToGs1ElementStrings")]
        [Xunit.TraitAttribute("Description", "Convert an uncompressed Digital Link to an element string")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/22/AJY3095721P49/10/ABC123", "010541234500001310ABC123<GS>22AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49/21/72292641703", "2172292641703<GS>22AJY3095721P49<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/10/ABC123/21/72292641703", "01054123450000132172292641703<GS>10ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8004/0541234537290A41%26GHpp33", "80040541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/10/ABC123", "10ABC123<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8004/0541234537290A41%26GHpp33/7040/5BVR", "70405BVR<GS>80040541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49/10/ABC123/21/72292641" +
            "703", "2172292641703<GS>10ABC123<GS>22AJY3095721P49<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/412/5060917510004", "4125060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/401/0541234537290A41%26GHpp33", "4010541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/417/5060917510004", "4175060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49", "22AJY3095721P49<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004/7040/5KFX", "414506091751000470405KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/410/5060917510004", "4105060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/22/AJY3095721P49/21/72292641703", "01054123450000132172292641703<GS>22AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/416/5060917510004", "4165060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8017/817019610850151481/8019/4003812", "80194003812<GS>8017817019610850151481", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201", "8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/411/5060917510004", "4115060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8017/817019610850151481", "8017817019610850151481", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004/254/RP56J920471", "4145060917510004254RP56J920471", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8010/0541234537290A41%23GH33", "80100541234537290A41#GH33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/415/5060917510004", "4155060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/10/ABC123", "010541234500001310ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8018/411369833821910265", "8018411369833821910265", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/402/21173492661712079", "40221173492661712079", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013", "0105412345000013", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/10/ABC123/21/72292641703", "2172292641703<GS>10ABC123<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/21/72292641703", "2172292641703<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8013/5060917511473062B98T", "80135060917511473062B98T", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/413/5060917510004", "4135060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/22/AJY3095721P49", "010541234500001322AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8018/411369833821910265/8019/4003812", "80194003812<GS>8018411369833821910265", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8010/0541234537290A41%23GH33/8011/6639047221", "80116639047221<GS>80100541234537290A41#GH33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/417/5060917510004/7040/5KFX", "417506091751000470405KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/00/998440410914660971", "00998440410914660971", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004", "4145060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/22/AJY3095721P49/10/ABC123/21/72292641703", "01054123450000132172292641703<GS>10ABC123<GS>22AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8003/04965031954585", "800304965031954585", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49/10/ABC123", "10ABC123<GS>22AJY3095721P49<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/21/72292641703", "01054123450000132172292641703", new string[0])]
        public async System.Threading.Tasks.Task ConvertAnUncompressedDigitalLinkToAnElementString(string digitalLink, string elementString, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("digitalLink", digitalLink);
            argumentsOfScenario.Add("elementString", elementString);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Convert an uncompressed Digital Link to an element string", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
    await testRunner.GivenAsync(string.Format("I want to convert the following compressed Digital Link to an element string: \"{0" +
                            "}\"", digitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 5
    await testRunner.WhenAsync("I convert the compressed Digital Link to an element string", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 6
    await testRunner.ThenAsync(string.Format("the element string should be \"{0}\"", elementString), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Convert an uncompressed Digital Link to an element string with brackets")]
        [Xunit.TraitAttribute("FeatureTitle", "Gs1CompressedDigitalLinkToGs1ElementStrings")]
        [Xunit.TraitAttribute("Description", "Convert an uncompressed Digital Link to an element string with brackets")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8018/411369833821910265/8019/4003812", "(8018)411369833821910265(8019)4003812", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/412/5060917510004", "(412)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/416/5060917510004", "(416)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/22/AJY3095721P49/10/ABC123", "(01)05412345000013(22)AJY3095721P49(10)ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8013/5060917511473062B98T", "(8013)5060917511473062B98T", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/10/ABC123", "(8006)054123450000130201(10)ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/10/ABC123/21/72292641703", "(8006)054123450000130201(10)ABC123(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8010/0541234537290A41%23GH33", "(8010)0541234537290A41#GH33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8004/0541234537290A41%26GHpp33/7040/5BVR", "(8004)0541234537290A41&GHpp33(7040)5BVR", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49", "(8006)054123450000130201(22)AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8003/04965031954585", "(8003)04965031954585", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/10/ABC123", "(01)05412345000013(10)ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/22/AJY3095721P49/10/ABC123/21/72292641703", "(01)05412345000013(22)AJY3095721P49(10)ABC123(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8018/411369833821910265", "(8018)411369833821910265", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/415/5060917510004", "(415)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49/21/72292641703", "(8006)054123450000130201(22)AJY3095721P49(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8017/817019610850151481/8019/4003812", "(8017)817019610850151481(8019)4003812", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013", "(01)05412345000013", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49/10/ABC123", "(8006)054123450000130201(22)AJY3095721P49(10)ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/21/72292641703", "(01)05412345000013(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/00/998440410914660971", "(00)998440410914660971", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/417/5060917510004/7040/5KFX", "(417)5060917510004(7040)5KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8004/0541234537290A41%26GHpp33", "(8004)0541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201", "(8006)054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/10/ABC123/21/72292641703", "(01)05412345000013(10)ABC123(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/22/AJY3095721P49", "(01)05412345000013(22)AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/402/21173492661712079", "(402)21173492661712079", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8010/0541234537290A41%23GH33/8011/6639047221", "(8010)0541234537290A41#GH33(8011)6639047221", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/21/72292641703", "(8006)054123450000130201(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/410/5060917510004", "(410)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/411/5060917510004", "(411)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/401/0541234537290A41%26GHpp33", "(401)0541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/417/5060917510004", "(417)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/22/AJY3095721P49/21/72292641703", "(01)05412345000013(22)AJY3095721P49(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8017/817019610850151481", "(8017)817019610850151481", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004/254/RP56J920471", "(414)5060917510004(254)RP56J920471", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004/7040/5KFX", "(414)5060917510004(7040)5KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/22/AJY3095721P49/10/ABC123/21/72292641" +
            "703", "(8006)054123450000130201(22)AJY3095721P49(10)ABC123(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004", "(414)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/413/5060917510004", "(413)5060917510004", new string[0])]
        public async System.Threading.Tasks.Task ConvertAnUncompressedDigitalLinkToAnElementStringWithBrackets(string digitalLink, string elementString, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("digitalLink", digitalLink);
            argumentsOfScenario.Add("elementString", elementString);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Convert an uncompressed Digital Link to an element string with brackets", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 51
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 52
    await testRunner.GivenAsync(string.Format("I want to convert the following compressed Digital Link to an element string: \"{0" +
                            "}\"", digitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 53
    await testRunner.WhenAsync("I convert the compressed Digital Link to an element string with brackets", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 54
    await testRunner.ThenAsync(string.Format("the element string should be \"{0}\"", elementString), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Convert an uncompressed Digital Link using short text to an element string")]
        [Xunit.TraitAttribute("FeatureTitle", "Gs1CompressedDigitalLinkToGs1ElementStrings")]
        [Xunit.TraitAttribute("Description", "Convert an uncompressed Digital Link using short text to an element string")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/lot/ABC123", "010541234500001310ABC123<GS>22AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/ser/72292641703", "2172292641703<GS>22AJY3095721P49<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/lot/ABC123/ser/72292641703", "01054123450000132172292641703<GS>10ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/giai/0541234537290A41%26GHpp33", "80040541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/lot/ABC123", "10ABC123<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/giai/0541234537290A41%26GHpp33/7040/5BVR", "70405BVR<GS>80040541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/lot/ABC123/ser/72292" +
            "641703", "2172292641703<GS>10ABC123<GS>22AJY3095721P49<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/purchasedFrom/5060917510004", "4125060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/ginc/0541234537290A41%26GHpp33", "4010541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/party/5060917510004", "4175060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49", "22AJY3095721P49<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gln/5060917510004/7040/5KFX", "414506091751000470405KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/shipTo/5060917510004", "4105060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/ser/72292641703", "01054123450000132172292641703<GS>22AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/glnProd/5060917510004", "4165060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrnp/817019610850151481/srin/4003812", "80194003812<GS>8017817019610850151481", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201", "8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/billTo/5060917510004", "4115060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrnp/817019610850151481", "8017817019610850151481", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gln/5060917510004/glnx/RP56J920471", "4145060917510004254RP56J920471", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/cpid/0541234537290A41%23GH33", "80100541234537290A41#GH33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/payTo/5060917510004", "4155060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/lot/ABC123", "010541234500001310ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrn/411369833821910265", "8018411369833821910265", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsin/21173492661712079", "40221173492661712079", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013", "0105412345000013", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/lot/ABC123/ser/72292641703", "2172292641703<GS>10ABC123<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/ser/72292641703", "2172292641703<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gmn/5060917511473062B98T", "80135060917511473062B98T", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/shipFor/5060917510004", "4135060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49", "010541234500001322AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrn/411369833821910265/srin/4003812", "80194003812<GS>8018411369833821910265", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/cpid/0541234537290A41%23GH33/cpsn/6639047221", "80116639047221<GS>80100541234537290A41#GH33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/party/5060917510004/7040/5KFX", "417506091751000470405KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/sscc/998440410914660971", "00998440410914660971", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gln/5060917510004", "4145060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/lot/ABC123/ser/722926417" +
            "03", "01054123450000132172292641703<GS>10ABC123<GS>22AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/grai/04965031954585", "800304965031954585", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/lot/ABC123", "10ABC123<GS>22AJY3095721P49<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/ser/72292641703", "01054123450000132172292641703", new string[0])]
        public async System.Threading.Tasks.Task ConvertAnUncompressedDigitalLinkUsingShortTextToAnElementString(string digitalLink, string elementString, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("digitalLink", digitalLink);
            argumentsOfScenario.Add("elementString", elementString);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Convert an uncompressed Digital Link using short text to an element string", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 99
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 100
    await testRunner.GivenAsync(string.Format("I want to convert the following compressed Digital Link to an element string: \"{0" +
                            "}\"", digitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 101
    await testRunner.WhenAsync("I convert the compressed Digital Link to an element string", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 102
    await testRunner.ThenAsync(string.Format("the element string should be \"{0}\"", elementString), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Convert an uncompressed Digital Link using short text to an element string with b" +
            "rackets")]
        [Xunit.TraitAttribute("FeatureTitle", "Gs1CompressedDigitalLinkToGs1ElementStrings")]
        [Xunit.TraitAttribute("Description", "Convert an uncompressed Digital Link using short text to an element string with b" +
            "rackets")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/ser/72292641703", "(01)05412345000013(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/cpid/0541234537290A41%23GH33", "(8010)0541234537290A41#GH33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gln/5060917510004", "(414)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/lot/ABC123", "(01)05412345000013(22)AJY3095721P49(10)ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrn/411369833821910265", "(8018)411369833821910265", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/lot/ABC123/ser/722926417" +
            "03", "(01)05412345000013(22)AJY3095721P49(10)ABC123(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/grai/04965031954585", "(8003)04965031954585", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/giai/0541234537290A41%26GHpp33", "(8004)0541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49", "(01)05412345000013(22)AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/party/5060917510004", "(417)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrnp/817019610850151481", "(8017)817019610850151481", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/lot/ABC123", "(8006)054123450000130201(10)ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201", "(8006)054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gln/5060917510004/7040/5KFX", "(414)5060917510004(7040)5KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49", "(8006)054123450000130201(22)AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrn/411369833821910265/srin/4003812", "(8018)411369833821910265(8019)4003812", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/ginc/0541234537290A41%26GHpp33", "(401)0541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/ser/72292641703", "(8006)054123450000130201(22)AJY3095721P49(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/lot/ABC123/ser/72292" +
            "641703", "(8006)054123450000130201(22)AJY3095721P49(10)ABC123(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/lot/ABC123/ser/72292641703", "(8006)054123450000130201(10)ABC123(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gmn/5060917511473062B98T", "(8013)5060917511473062B98T", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gln/5060917510004/glnx/RP56J920471", "(414)5060917510004(254)RP56J920471", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013", "(01)05412345000013", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/billTo/5060917510004", "(411)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/party/5060917510004/7040/5KFX", "(417)5060917510004(7040)5KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/giai/0541234537290A41%26GHpp33/7040/5BVR", "(8004)0541234537290A41&GHpp33(7040)5BVR", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsin/21173492661712079", "(402)21173492661712079", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/cpv/AJY3095721P49/lot/ABC123", "(8006)054123450000130201(22)AJY3095721P49(10)ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/lot/ABC123/ser/72292641703", "(01)05412345000013(10)ABC123(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/payTo/5060917510004", "(415)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/cpid/0541234537290A41%23GH33/cpsn/6639047221", "(8010)0541234537290A41#GH33(8011)6639047221", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/sscc/998440410914660971", "(00)998440410914660971", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/lot/ABC123", "(01)05412345000013(10)ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/shipFor/5060917510004", "(413)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gtin/05412345000013/cpv/AJY3095721P49/ser/72292641703", "(01)05412345000013(22)AJY3095721P49(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/glnProd/5060917510004", "(416)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/itip/054123450000130201/ser/72292641703", "(8006)054123450000130201(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/purchasedFrom/5060917510004", "(412)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/shipTo/5060917510004", "(410)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gsrnp/817019610850151481/srin/4003812", "(8017)817019610850151481(8019)4003812", new string[0])]
        public async System.Threading.Tasks.Task ConvertAnUncompressedDigitalLinkUsingShortTextToAnElementStringWithBrackets(string digitalLink, string elementString, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("digitalLink", digitalLink);
            argumentsOfScenario.Add("elementString", elementString);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Convert an uncompressed Digital Link using short text to an element string with b" +
                    "rackets", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 147
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 148
    await testRunner.GivenAsync(string.Format("I want to convert the following compressed Digital Link to an element string: \"{0" +
                            "}\"", digitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 149
    await testRunner.WhenAsync("I convert the compressed Digital Link to an element string with brackets", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 150
    await testRunner.ThenAsync(string.Format("the element string should be \"{0}\"", elementString), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Convert a compressed Digital Link for a medicinal identifier to an element string" +
            "")]
        [Xunit.TraitAttribute("FeatureTitle", "Gs1CompressedDigitalLinkToGs1ElementStrings")]
        [Xunit.TraitAttribute("Description", "Convert a compressed Digital Link for a medicinal identifier to an element string" +
            "")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/10/ABC123/21/72292641703", "01054123450000132172292641703<GS>10ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/10/ABC123/21/72292641703?17=290331", "0105412345000013172903312172292641703<GS>10ABC123", new string[0])]
        public async System.Threading.Tasks.Task ConvertACompressedDigitalLinkForAMedicinalIdentifierToAnElementString(string digitalLink, string elementString, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("digitalLink", digitalLink);
            argumentsOfScenario.Add("elementString", elementString);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Convert a compressed Digital Link for a medicinal identifier to an element string" +
                    "", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 195
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 196
    await testRunner.GivenAsync(string.Format("I want to convert the following compressed Digital Link to an element string: \"{0" +
                            "}\"", digitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 197
    await testRunner.WhenAsync("I convert the compressed Digital Link to an element string", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 198
    await testRunner.ThenAsync(string.Format("the element string should be \"{0}\"", elementString), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Convert a compressed Digital Link for a medicinal identifier to an element string" +
            " with brackets")]
        [Xunit.TraitAttribute("FeatureTitle", "Gs1CompressedDigitalLinkToGs1ElementStrings")]
        [Xunit.TraitAttribute("Description", "Convert a compressed Digital Link for a medicinal identifier to an element string" +
            " with brackets")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/10/ABC123/21/72292641703", "(01)05412345000013(10)ABC123(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/10/ABC123/21/72292641703?17=290331", "(01)05412345000013(10)ABC123(21)72292641703(17)290331", new string[0])]
        public async System.Threading.Tasks.Task ConvertACompressedDigitalLinkForAMedicinalIdentifierToAnElementStringWithBrackets(string digitalLink, string elementString, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("digitalLink", digitalLink);
            argumentsOfScenario.Add("elementString", elementString);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Convert a compressed Digital Link for a medicinal identifier to an element string" +
                    " with brackets", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 205
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 206
    await testRunner.GivenAsync(string.Format("I want to convert the following compressed Digital Link to an element string: \"{0" +
                            "}\"", digitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 207
    await testRunner.WhenAsync("I convert the compressed Digital Link to an element string with brackets", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 208
    await testRunner.ThenAsync(string.Format("the element string should be \"{0}\"", elementString), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Convert a partially compressed Digital Link to an element string")]
        [Xunit.TraitAttribute("FeatureTitle", "Gs1CompressedDigitalLinkToGs1ElementStrings")]
        [Xunit.TraitAttribute("Description", "Convert a partially compressed Digital Link to an element string")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8017/817019610850151481/gBlz0X5A", "80194003812<GS>8017817019610850151481", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8010/0541234537290A41%23GH33/gBGmLt9I1", "80116639047221<GS>80100541234537290A41#GH33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/416/5060917510004", "4165060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/417/5060917510004/cEBWUKu", "417506091751000470405KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8010/0541234537290A41%23GH33", "80100541234537290A41#GH33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/I1j3FSNWcOGeFywaR5CZm", "01054123450000132358TFV883a904GH&3", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/417/5060917510004", "4175060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8004/0541234537290A41%26GHpp33", "80040541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/EEarwSM", "10ABC123<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/253/3060077601309", "2533060077601309", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8004/0541234537290A41%26GHpp33/cEB2Cqi", "70407BVR<GS>80040541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/EEarwSMhC4an0V04", "010541234500001310ABC123<GS>2172292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/402/21173492661712079", "40221173492661712079", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013", "0105412345000013", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/255/5678409730535", "2555678409730535", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/EEarwSMhC4an0V05E2gEsb6e897an8eg", "10ABC123<GS>2172292641703<GS>22AJY3095721P49<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004/JUa0T-eifdtOO9Q", "4145060917510004254RP56J920471", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8018/411369833821910265", "8018411369833821910265", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/410/5060917510004", "4105060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/415/5060917510004", "4155060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/Im0AljfT3nvbU_j0", "010541234500001322AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004/cEBWUKu", "414506091751000470405KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/IQuGp9FdO", "2172292641703<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201", "8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/IQuGp9FdO", "01054123450000132172292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8018/411369833821910265/gBlz0X5A", "80194003812<GS>8018411369833821910265", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/EEarwSMibQCWN9Pee9tT-PQ", "010541234500001310ABC123<GS>22AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/IQuGp9FdORNoBLG-nvPe2p_Ho", "01054123450000132172292641703<GS>22AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004", "4145060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/EEarwSMhC4an0V05E2gEsb6e897an8eg", "010541234500001310ABC123<GS>2172292641703<GS>22AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/412/5060917510004", "4125060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/413/5060917510004", "4135060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/IQuGp9FdORNoBLG-nvPe2p_Ho", "2172292641703<GS>22AJY3095721P49<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8013/5060917511473062B98T", "80135060917511473062B98T", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8017/817019610850151481", "8017817019610850151481", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/401/0541234537290A41%26GHpp33", "4010541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/Im0AljfT3nvbU_j0", "22AJY3095721P49<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/411/5060917510004", "4115060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/EEarwSM", "010541234500001310ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/EEarwSMibQCWN9Pee9tT-PQ", "10ABC123<GS>22AJY3095721P49<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/00/998440410914660971", "00998440410914660971", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8003/04965031954585", "800304965031954585", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/EEarwSMhC4an0V04", "10ABC123<GS>2172292641703<GS>8006054123450000130201", new string[0])]
        public async System.Threading.Tasks.Task ConvertAPartiallyCompressedDigitalLinkToAnElementString(string digitalLink, string elementString, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("digitalLink", digitalLink);
            argumentsOfScenario.Add("elementString", elementString);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Convert a partially compressed Digital Link to an element string", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 215
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 216
    await testRunner.GivenAsync(string.Format("I want to convert the following compressed Digital Link to an element string: \"{0" +
                            "}\"", digitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 217
    await testRunner.WhenAsync("I convert the compressed Digital Link to an element string", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 218
    await testRunner.ThenAsync(string.Format("the element string should be \"{0}\"", elementString), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Convert a partially compressed Digital Link to an element string with brackets")]
        [Xunit.TraitAttribute("FeatureTitle", "Gs1CompressedDigitalLinkToGs1ElementStrings")]
        [Xunit.TraitAttribute("Description", "Convert a partially compressed Digital Link to an element string with brackets")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013", "(01)05412345000013", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/413/5060917510004", "(413)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8004/0541234537290A41%26GHpp33", "(8004)0541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/IQuGp9FdO", "(8006)054123450000130201(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8010/0541234537290A41%23GH33", "(8010)0541234537290A41#GH33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/Im0AljfT3nvbU_j0", "(8006)054123450000130201(22)AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004/cEBWUKu", "(414)5060917510004(7040)5KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/411/5060917510004", "(411)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8018/411369833821910265", "(8018)411369833821910265", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004", "(414)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/EEarwSMibQCWN9Pee9tT-PQ", "(01)05412345000013(22)AJY3095721P49(10)ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/416/5060917510004", "(416)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/EEarwSMhC4an0V04", "(01)05412345000013(10)ABC123(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/417/5060917510004/cEBWUKu", "(417)5060917510004(7040)5KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8017/817019610850151481/gBlz0X5A", "(8017)817019610850151481(8019)4003812", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/410/5060917510004", "(410)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/401/0541234537290A41%26GHpp33", "(401)0541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/412/5060917510004", "(412)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201", "(8006)054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8017/817019610850151481", "(8017)817019610850151481", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/IQuGp9FdORNoBLG-nvPe2p_Ho", "(8006)054123450000130201(22)AJY3095721P49(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/IQuGp9FdO", "(01)05412345000013(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/00/998440410914660971", "(00)998440410914660971", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/EEarwSMibQCWN9Pee9tT-PQ", "(8006)054123450000130201(22)AJY3095721P49(10)ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/253/3060077601309", "(253)3060077601309", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/IQuGp9FdORNoBLG-nvPe2p_Ho", "(01)05412345000013(22)AJY3095721P49(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8003/04965031954585", "(8003)04965031954585", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/414/5060917510004/JUa0T-eifdtOO9Q", "(414)5060917510004(254)RP56J920471", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/Im0AljfT3nvbU_j0", "(01)05412345000013(22)AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/EEarwSMhC4an0V05E2gEsb6e897an8eg", "(01)05412345000013(22)AJY3095721P49(10)ABC123(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/I1j3FSNWcOGeFywaR5CZm", "(01)05412345000013(235)8TFV883a904GH&3", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/255/5678409730535", "(255)5678409730535", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8010/0541234537290A41%23GH33/gBGmLt9I1", "(8010)0541234537290A41#GH33(8011)6639047221", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/417/5060917510004", "(417)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/01/05412345000013/EEarwSM", "(01)05412345000013(10)ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/EEarwSMhC4an0V05E2gEsb6e897an8eg", "(8006)054123450000130201(22)AJY3095721P49(10)ABC123(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8018/411369833821910265/gBlz0X5A", "(8018)411369833821910265(8019)4003812", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/EEarwSMhC4an0V04", "(8006)054123450000130201(10)ABC123(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/415/5060917510004", "(415)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8004/0541234537290A41%26GHpp33/cEB2Cqi", "(8004)0541234537290A41&GHpp33(7040)7BVR", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/402/21173492661712079", "(402)21173492661712079", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8013/5060917511473062B98T", "(8013)5060917511473062B98T", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/8006/054123450000130201/EEarwSM", "(8006)054123450000130201(10)ABC123", new string[0])]
        public async System.Threading.Tasks.Task ConvertAPartiallyCompressedDigitalLinkToAnElementStringWithBrackets(string digitalLink, string elementString, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("digitalLink", digitalLink);
            argumentsOfScenario.Add("elementString", elementString);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Convert a partially compressed Digital Link to an element string with brackets", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 266
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 267
    await testRunner.GivenAsync(string.Format("I want to convert the following compressed Digital Link to an element string: \"{0" +
                            "}\"", digitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 268
    await testRunner.WhenAsync("I convert the compressed Digital Link to an element string with brackets", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 269
    await testRunner.ThenAsync(string.Format("the element string should be \"{0}\"", elementString), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Convert a compressed Digital Link to an element string")]
        [Xunit.TraitAttribute("FeatureTitle", "Gs1CompressedDigitalLinkToGs1ElementStrings")]
        [Xunit.TraitAttribute("Description", "Convert a compressed Digital Link to an element string")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QTSaVjC_dA", "4135060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBCVYNWjFkzaNWbdk5YQWjFHHkM2Y", "80100541234537290A41#GH33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmkTaASxvp7z3tqfx6", "010541234500001322AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/cEB2CqjAAkuwatGLJm0as27JywgtGKaPI4cGbM", "70407BVR<GS>80040541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QSSaVjC_dA", "4125060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmkIXDU-iun", "01054123450000132172292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QCJZyW9mC6Z4", "40221173492661712079", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/JVUqG5hJ5wA", "2555678409730535", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QBl2DVoxZM2jVm3ZOWEFoxTR5HDgzZg", "4010541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QXSaVjC_dHBAVlCrg", "417506091751000470405KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/JTLIetaiHYA", "2533060077601309", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/JUa0T-eifdtOO9UFEmlYwv3Q", "4145060917510004254RP56J920471", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QUSaVjC_dHBAVlCrg", "414506091751000470405KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gAYMBI_bNGwJk", "8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QQSaVjC_dA", "4105060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/EEarwSMhC4an0V08ADBgJH7Zo2BMg", "10ABC123<GS>2172292641703<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/EEarwSOABgwEj9s0bAmQ", "10ABC123<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmg", "0105412345000013", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/EEarwSMhC4an0V05E2gEsb6e897an8ewAMGAkftmjYEy", "10ABC123<GS>2172292641703<GS>22AJY3095721P49<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmiCNV4JGQhcNT6K6c", "010541234500001310ABC123<GS>2172292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gASXYNWjFkzaNWbdk5YQWjFNHkcODNm", "80040541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QVSaVjC_dA", "4155060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmkax7ipGrOHDPC5YNI8hMz", "01054123450000132358TFV883a904GH&3", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AN2yxDhfaiaw", "00998440410914660971", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/Im0AljfT3nvbU_j2ABgwEj9s0bAmQ", "22AJY3095721P49<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QWSaVjC_dA", "4165060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmiCNV4JG", "010541234500001310ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBe1ajAd9ATDmAGXPRfk", "8017817019610850151481<GS>80194003812", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBCVYNWjFkzaNWbdk5YQWjFHHkM2cAI0xdvpGo", "80100541234537290A41#GH33<GS>80116639047221", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBhbV6rzBENPk", "8018411369833821910265", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gAMJCAXukTMA", "800304965031954585", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QUSaVjC_dA", "4145060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QRSaVjC_dA", "4115060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/EEarwSMibQCWN9Pee9tT-PYAGDASP2zRsCZ", "10ABC123<GS>22AJY3095721P49<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmiCNV4JGRNoBLG-nvPe2p_Ho", "010541234500001310ABC123<GS>22AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/IQuGp9FdORNoBLG-nvPe2p_HsADBgJH7Zo2BMg", "2172292641703<GS>22AJY3095721P49<GS>8006054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBN05060917511473062B98T", "80135060917511473062B98T", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBhbV6rzBENPmAGXPRfk", "8018411369833821910265<GS>80194003812", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QXSaVjC_dA", "4175060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmiCNV4JGQhcNT6K6cibQCWN9Pee9tT-PQ", "010541234500001310ABC123<GS>2172292641703<GS>22AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBe1ajAd9ATDk", "8017817019610850151481", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmkIXDU-iunIm0AljfT3nvbU_j0", "01054123450000132172292641703<GS>22AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/IQuGp9FdPAAwYCR-2aNgTI", "2172292641703<GS>8006054123450000130201", new string[0])]
        public async System.Threading.Tasks.Task ConvertACompressedDigitalLinkToAnElementString(string digitalLink, string elementString, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("digitalLink", digitalLink);
            argumentsOfScenario.Add("elementString", elementString);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Convert a compressed Digital Link to an element string", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 317
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 318
    await testRunner.GivenAsync(string.Format("I want to convert the following compressed Digital Link to an element string: \"{0" +
                            "}\"", digitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 319
    await testRunner.WhenAsync("I convert the compressed Digital Link to an element string", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 320
    await testRunner.ThenAsync(string.Format("the element string should be \"{0}\"", elementString), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Convert a compressed Digital Link to an element string with brackets")]
        [Xunit.TraitAttribute("FeatureTitle", "Gs1CompressedDigitalLinkToGs1ElementStrings")]
        [Xunit.TraitAttribute("Description", "Convert a compressed Digital Link to an element string with brackets")]
        [Xunit.InlineDataAttribute("https://id.gs1.org/JVUqG5hJ5wA", "(255)5678409730535", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QCJZyW9mC6Z4", "(402)21173492661712079", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QRSaVjC_dA", "(411)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBN05060917511473062B98T", "(8013)5060917511473062B98T", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QXSaVjC_dA", "(417)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmiCNV4JGQhcNT6K6cibQCWN9Pee9tT-PQ", "(01)05412345000013(22)AJY3095721P49(10)ABC123(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmg", "(01)05412345000013", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QBl2DVoxZM2jVm3ZOWEFoxTR5HDgzZg", "(401)0541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AN2yxDhfaiaw", "(00)998440410914660971", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmkax7ipGrOHDPC5YNI8hMz", "(01)05412345000013(235)8TFV883a904GH&3", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/JTLIetaiHYA", "(253)3060077601309", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBCVYNWjFkzaNWbdk5YQWjFHHkM2Y", "(8010)0541234537290A41#GH33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmiCNV4JGQhcNT6K6c", "(01)05412345000013(10)ABC123(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QVSaVjC_dA", "(415)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QUSaVjC_dHBAVlCrg", "(414)5060917510004(7040)5KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/Im0AljfT3nvbU_j2ABgwEj9s0bAmQ", "(8006)054123450000130201(22)AJY3095721P49", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBe1ajAd9ATDk", "(8017)817019610850151481", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/cEB2CqjAAkuwatGLJm0as27JywgtGKaPI4cGbM", "(8004)0541234537290A41&GHpp33(7040)7BVR", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/EEarwSOABgwEj9s0bAmQ", "(8006)054123450000130201(10)ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QTSaVjC_dA", "(413)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmkIXDU-iun", "(01)05412345000013(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBCVYNWjFkzaNWbdk5YQWjFHHkM2cAI0xdvpGo", "(8010)0541234537290A41#GH33(8011)6639047221", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/EEarwSMhC4an0V05E2gEsb6e897an8ewAMGAkftmjYEy", "(8006)054123450000130201(22)AJY3095721P49(10)ABC123(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmkIXDU-iunIm0AljfT3nvbU_j0", "(01)05412345000013(22)AJY3095721P49(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/EEarwSMibQCWN9Pee9tT-PYAGDASP2zRsCZ", "(8006)054123450000130201(22)AJY3095721P49(10)ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QSSaVjC_dA", "(412)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBhbV6rzBENPmAGXPRfk", "(8018)411369833821910265(8019)4003812", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QWSaVjC_dA", "(416)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gAMJCAXukTMA", "(8003)04965031954585", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmiCNV4JGRNoBLG-nvPe2p_Ho", "(01)05412345000013(22)AJY3095721P49(10)ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/IQuGp9FdORNoBLG-nvPe2p_HsADBgJH7Zo2BMg", "(8006)054123450000130201(22)AJY3095721P49(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmiCNV4JG", "(01)05412345000013(10)ABC123", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QUSaVjC_dA", "(414)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBhbV6rzBENPk", "(8018)411369833821910265", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/EEarwSMhC4an0V08ADBgJH7Zo2BMg", "(8006)054123450000130201(10)ABC123(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gAYMBI_bNGwJk", "(8006)054123450000130201", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QXSaVjC_dHBAVlCrg", "(417)5060917510004(7040)5KFX", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/IQuGp9FdPAAwYCR-2aNgTI", "(8006)054123450000130201(21)72292641703", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gBe1ajAd9ATDmAGXPRfk", "(8017)817019610850151481(8019)4003812", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/QQSaVjC_dA", "(410)5060917510004", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/JUa0T-eifdtOO9UFEmlYwv3Q", "(414)5060917510004(254)RP56J920471", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/gASXYNWjFkzaNWbdk5YQWjFNHkcODNm", "(8004)0541234537290A41&GHpp33", new string[0])]
        [Xunit.InlineDataAttribute("https://id.gs1.org/AQnYUc1gmkTaASxvp7z3tqfx6", "(01)05412345000013(22)AJY3095721P49", new string[0])]
        public async System.Threading.Tasks.Task ConvertACompressedDigitalLinkToAnElementStringWithBrackets(string digitalLink, string elementString, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("digitalLink", digitalLink);
            argumentsOfScenario.Add("elementString", elementString);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Convert a compressed Digital Link to an element string with brackets", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 368
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 369
    await testRunner.GivenAsync(string.Format("I want to convert the following compressed Digital Link to an element string: \"{0" +
                            "}\"", digitalLink), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 370
    await testRunner.WhenAsync("I convert the compressed Digital Link to an element string with brackets", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 371
    await testRunner.ThenAsync(string.Format("the element string should be \"{0}\"", elementString), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await Gs1CompressedDigitalLinkToGs1ElementStringsFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await Gs1CompressedDigitalLinkToGs1ElementStringsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
