// --------------------------------------------------------------------------
// <copyright file="FormatTable.cs" company="Solidsoft Reply Ltd.">
// Copyright © 2025 Solidsoft Reply Ltd. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
// <summary>
// Represents the format table.
// </summary>
// --------------------------------------------------------------------------
// The code in this file is derived in part from the GS1 Digital Link
// Compression Prototype which is licenced under the Apache License,
// Version 2.0.
//
// Copyright 2019 GS1 AISBL
//
// See https://github.com/gs1/GS1DigitalLinkCompressionPrototype for
// further details.
// --------------------------------------------------------------------------

namespace Solidsoft.Reply.Gs1DigitalLinkLib.Internal;

using System.Collections;
using System.Diagnostics.CodeAnalysis;

/// <summary>
/// Represents the format table.
/// </summary>
internal class FormatTable : IReadOnlyDictionary<string, FormatElements> {

    /// <summary>
    /// The format table.
    /// </summary>
    private static readonly IReadOnlyDictionary<string, FormatElements> _formatTable;

    /// <summary>
    /// Initializes static members of the <see cref="FormatTable"/> class.
    /// </summary>
    static FormatTable() =>
        _formatTable = new Dictionary<string, FormatElements> {
            { "00", [new ExpectedLength(ExpectedTypes.Numeric, 18)] },
            { "01", [new ExpectedLength(ExpectedTypes.Numeric, 14)] },
            { "02", [new ExpectedLength(ExpectedTypes.Numeric, 14)] },
            { "10", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 20)] },
            { "11", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "12", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "13", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "15", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "16", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "17", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "20", [new ExpectedLength(ExpectedTypes.Numeric, 2)] },
            { "21", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 20)] },
            { "22", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 20)] },
            { "235", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 28)] },
            { "240", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "241", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "242", [new ExpectedMaxLength(ExpectedTypes.Numeric, 6)] },
            { "243", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 20)] },
            { "250", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "251", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "253", [new ExpectedLength(ExpectedTypes.Numeric, 13), new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 17)] },
            { "254", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 20)] },
            { "255", [new ExpectedLength(ExpectedTypes.Numeric, 13), new ExpectedMaxLength(ExpectedTypes.Numeric, 12)] },
            { "30", [new ExpectedMaxLength(ExpectedTypes.Numeric, 8)] },
            { "3100", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3101", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3102", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3103", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3104", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3105", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3110", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3111", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3112", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3113", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3114", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3115", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3120", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3121", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3122", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3123", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3124", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3125", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3130", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3131", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3132", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3133", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3134", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3135", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3140", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3141", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3142", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3143", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3144", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3145", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3150", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3151", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3152", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3153", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3154", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3155", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3160", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3161", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3162", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3163", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3164", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3165", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3200", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3201", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3202", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3203", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3204", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3205", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3210", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3211", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3212", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3213", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3214", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3215", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3220", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3221", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3222", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3223", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3224", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3225", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3230", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3231", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3232", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3233", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3234", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3235", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3240", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3241", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3242", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3243", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3244", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3245", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3250", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3251", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3252", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3253", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3254", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3255", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3260", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3261", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3262", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3263", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3264", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3265", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3270", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3271", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3272", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3273", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3274", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3275", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3280", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3281", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3282", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3283", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3284", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3285", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3290", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3291", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3292", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3293", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3294", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3295", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3300", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3301", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3302", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3303", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3304", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3305", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3310", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3311", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3312", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3313", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3314", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3315", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3320", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3321", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3322", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3323", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3324", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3325", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3330", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3331", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3332", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3333", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3334", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3335", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3340", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3341", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3342", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3343", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3344", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3345", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3350", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3351", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3352", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3353", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3354", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3355", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3360", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3361", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3362", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3363", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3364", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3365", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3370", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3371", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3372", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3373", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3374", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3375", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3400", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3401", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3402", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3403", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3404", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3405", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3410", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3411", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3412", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3413", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3414", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3415", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3420", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3421", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3422", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3423", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3424", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3425", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3430", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3431", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3432", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3433", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3434", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3435", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3440", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3441", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3442", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3443", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3444", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3445", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3450", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3451", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3452", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3453", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3454", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3455", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3460", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3461", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3462", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3463", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3464", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3465", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3470", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3471", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3472", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3473", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3474", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3475", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3480", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3481", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3482", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3483", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3484", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3485", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3490", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3491", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3492", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3493", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3494", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3495", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3500", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3501", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3502", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3503", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3504", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3505", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3510", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3511", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3512", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3513", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3514", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3515", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3520", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3521", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3522", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3523", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3524", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3525", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3530", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3531", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3532", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3533", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3534", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3535", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3540", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3541", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3542", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3543", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3544", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3545", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3550", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3551", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3552", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3553", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3554", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3555", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3560", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3561", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3562", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3563", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3564", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3565", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3570", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3571", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3572", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3573", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3574", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3575", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3600", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3601", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3602", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3603", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3604", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3605", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3610", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3611", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3612", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3613", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3614", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3615", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3620", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3621", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3622", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3623", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3624", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3625", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3630", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3631", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3632", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3633", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3634", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3635", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3640", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3641", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3642", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3643", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3644", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3645", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3650", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3651", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3652", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3653", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3654", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3655", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3660", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3661", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3662", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3663", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3664", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3665", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3670", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3671", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3672", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3673", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3674", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3675", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3680", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3681", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3682", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3683", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3684", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3685", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3690", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3691", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3692", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3693", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3694", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3695", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "37", [new ExpectedMaxLength(ExpectedTypes.Numeric, 8)] },
            { "3900", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3901", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3902", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3903", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3904", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3905", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3906", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3907", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3908", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3909", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3910", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3911", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3912", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3913", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3914", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3915", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3916", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3917", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3918", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3919", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3920", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3921", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3922", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3923", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3924", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3925", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3926", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3927", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3928", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3929", [new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3930", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3931", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3932", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3933", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3934", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3935", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3936", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3937", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3938", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3939", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 15)] },
            { "3940", [new ExpectedLength(ExpectedTypes.Numeric, 4)] },
            { "3941", [new ExpectedLength(ExpectedTypes.Numeric, 4)] },
            { "3942", [new ExpectedLength(ExpectedTypes.Numeric, 4)] },
            { "3943", [new ExpectedLength(ExpectedTypes.Numeric, 4)] },
            { "3950", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3951", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3952", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3953", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3954", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3955", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3956", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3957", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3958", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "3959", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "400", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "401", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "402", [new ExpectedLength(ExpectedTypes.Numeric, 17)] },
            { "403", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "410", [new ExpectedLength(ExpectedTypes.Numeric, 13)] },
            { "411", [new ExpectedLength(ExpectedTypes.Numeric, 13)] },
            { "412", [new ExpectedLength(ExpectedTypes.Numeric, 13)] },
            { "413", [new ExpectedLength(ExpectedTypes.Numeric, 13)] },
            { "414", [new ExpectedLength(ExpectedTypes.Numeric, 13)] },
            { "415", [new ExpectedLength(ExpectedTypes.Numeric, 13)] },
            { "416", [new ExpectedLength(ExpectedTypes.Numeric, 13)] },
            { "417", [new ExpectedLength(ExpectedTypes.Numeric, 13)] },
            { "420", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 20)] },
            { "421", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 9)] },
            { "422", [new ExpectedLength(ExpectedTypes.Numeric, 3)] },
            { "423", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 12)] },
            { "424", [new ExpectedLength(ExpectedTypes.Numeric, 3)] },
            { "425", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Numeric, 12)] },
            { "426", [new ExpectedLength(ExpectedTypes.Numeric, 3)] },
            { "427", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 3)] },
            { "4300", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 35)] },
            { "4301", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 35)] },
            { "4302", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 70)] },
            { "4303", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 70)] },
            { "4304", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 70)] },
            { "4305", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 70)] },
            { "4306", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 70)] },
            { "4307", [new ExpectedLength(ExpectedTypes.Alphanumeric, 2)] },
            { "4308", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "4309", [new ExpectedMaxLength(ExpectedTypes.Numeric, 20)] },
            { "4310", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 35)] },
            { "4311", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 35)] },
            { "4312", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 70)] },
            { "4313", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 70)] },
            { "4314", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 70)] },
            { "4315", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 70)] },
            { "4316", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 70)] },
            { "4317", [new ExpectedLength(ExpectedTypes.Alphanumeric, 2)] },
            { "4318", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 20)] },
            { "4319", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "4320", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 35)] },
            { "4321", [new ExpectedLength(ExpectedTypes.Numeric, 1)] },
            { "4322", [new ExpectedLength(ExpectedTypes.Numeric, 1)] },
            { "4323", [new ExpectedLength(ExpectedTypes.Numeric, 1)] },
            { "4324", [new ExpectedLength(ExpectedTypes.Numeric, 10)] },
            { "4325", [new ExpectedLength(ExpectedTypes.Numeric, 10)] },
            { "4326", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "7001", [new ExpectedLength(ExpectedTypes.Numeric, 13)] },
            { "7002", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "7003", [new ExpectedLength(ExpectedTypes.Numeric, 10)] },
            { "7004", [new ExpectedMaxLength(ExpectedTypes.Numeric, 4)] },
            { "7005", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 12)] },
            { "7006", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "7007", [new ExpectedLength(ExpectedTypes.Numeric, 6), new ExpectedMaxLength(ExpectedTypes.Numeric, 6)] },
            { "7008", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 3)] },
            { "7009", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 10)] },
            { "7010", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 2)] },
            { "7020", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 20)] },
            { "7021", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 20)] },
            { "7022", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 20)] },
            { "7023", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "7030", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 27)] },
            { "7031", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 27)] },
            { "7032", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 27)] },
            { "7033", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 27)] },
            { "7034", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 27)] },
            { "7035", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 27)] },
            { "7036", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 27)] },
            { "7037", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 27)] },
            { "7038", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 27)] },
            { "7039", [new ExpectedLength(ExpectedTypes.Numeric, 3), new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 27)] },
            { "7040", [new ExpectedLength(ExpectedTypes.Numeric, 1), new ExpectedLength(ExpectedTypes.Alphanumeric, 3)] },
            { "710", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 20)] },
            { "711", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 20)] },
            { "712", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 20)] },
            { "713", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 20)] },
            { "714", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 20)] },
            { "7230", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "7231", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "7232", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "7233", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "7234", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "7235", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "7236", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "7237", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "7238", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "7239", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "7240", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 20)] },
            { "8001", [new ExpectedLength(ExpectedTypes.Numeric, 14)] },
            { "8002", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 20)] },
            { "8003", [new ExpectedLength(ExpectedTypes.Numeric, 14), new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 16)] },
            { "8004", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "8005", [new ExpectedLength(ExpectedTypes.Numeric, 6)] },
            { "8006", [new ExpectedLength(ExpectedTypes.Numeric, 18)] },
            { "8007", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 24)] },
            { "8008", [new ExpectedLength(ExpectedTypes.Numeric, 8), new ExpectedMaxLength(ExpectedTypes.Numeric, 4)] },
            { "8009", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 50)] },
            { "8010", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "8011", [new ExpectedMaxLength(ExpectedTypes.Numeric, 12)] },
            { "8012", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 20)] },
            { "8013", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 25)] },
            { "8017", [new ExpectedLength(ExpectedTypes.Numeric, 18)] },
            { "8018", [new ExpectedLength(ExpectedTypes.Numeric, 18)] },
            { "8019", [new ExpectedMaxLength(ExpectedTypes.Numeric, 10)] },
            { "8020", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 25)] },
            { "8026", [new ExpectedLength(ExpectedTypes.Numeric, 18)] },
            { "8110", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 70)] },
            { "8111", [new ExpectedLength(ExpectedTypes.Numeric, 4)] },
            { "8112", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 70)] },
            { "8200", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 70)] },
            { "90", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 30)] },
            { "91", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 90)] },
            { "92", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 90)] },
            { "93", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 90)] },
            { "94", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 90)] },
            { "95", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 90)] },
            { "96", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 90)] },
            { "97", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 90)] },
            { "98", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 90)] },
            { "99", [new ExpectedMaxLength(ExpectedTypes.Alphanumeric, 90)] }
        };

    /// <summary>
    /// Initializes a new instance of the <see cref="FormatTable"/> class.
    /// </summary>
    private FormatTable() {
    }

    /// <summary>
    /// Gets the AI keys.
    /// </summary>
    public IEnumerable<string> Keys => _formatTable.Keys;

    /// <summary>
    /// Gets the format elements.
    /// </summary>
    public IEnumerable<FormatElements> Values => _formatTable.Values;

    /// <summary>
    /// Gets the count of format elements.
    /// </summary>
    public int Count => _formatTable.Count;

    /// <summary>
    /// Gets the <see cref="FormatElements"/> with the specified AI key.
    /// </summary>
    /// <param name="key">The AI key.</param>
    /// <returns>The format item dictionary.</returns>
    public FormatElements this[string key] => _formatTable[key];

    /// <summary>
    /// Factory method to create a new <see cref="FormatTable"/> instance.
    /// </summary>
    /// <returns>An <see cref="FormatTable"/> instance.</returns>
    public static FormatTable Create() => [];

    /// <summary>
    /// Tries to get the format elements with the specified AI key.
    /// </summary>
    /// <param name="key">The AI key.</param>
    /// <param name="value">The format elements.</param>
    /// <returns>True, if the AI key was found; otherwise false.</returns>
    public bool TryGetValue(string key, [MaybeNullWhen(false)] out FormatElements value) =>
        _formatTable.TryGetValue(key, out value);

    /// <summary>
    /// Determines whether the format table contains the specified AI key.
    /// </summary>
    /// <param name="key">The AI key.</param>
    /// <returns>True, if the format table contains the AI key; otherwise false.</returns>
    public bool ContainsKey(string key) => _formatTable.ContainsKey(key);

    /// <summary>
    /// Gets the enumerator for the format table.
    /// </summary>
    /// <returns>The enumerator for the format table.</returns>
    public IEnumerator<KeyValuePair<string, FormatElements>> GetEnumerator() =>
        _formatTable.GetEnumerator();

    /// <summary>
    /// Gets the enumerator for the format table.
    /// </summary>
    /// <returns>The enumerator for the format table.</returns>
    IEnumerator IEnumerable.GetEnumerator() =>
        _formatTable.GetEnumerator();
}