// --------------------------------------------------------------------------
// <copyright file="DigitalLinkExtensions.cs" company="Solidsoft Reply Ltd.">
// Copyright © 2025 Solidsoft Reply Ltd. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
// <summary>
// Extension methods for converting GS1 Digital Link data between different representations.
// </summary>
// --------------------------------------------------------------------------

namespace Solidsoft.Reply.Gs1DigitalLinkLib;

/// <summary>
/// Extension methods for converting GS1 Digital Link data between different representations.
/// </summary>
public static partial class DigitalLinkExtensions {

    /// <summary>
    /// Returns an dictionary of Application Identifiers and their values for a given element string.
    /// </summary>
    /// <param name="elementString">The element string.</param>
    /// <param name="noValidation">
    /// If true, the element string is not validated. The GS1 AI dictionary may contain invalid AIs and AI values.
    /// </param>
    /// <returns>A dictionary of AIs and AI values.</returns>
    /// <exception cref="ArgumentException">The element string is invalid.</exception>
    /// <remarks>The element string may be in one of two forms.
    /// <para>
    /// <list type="number">
    ///     <item>
    ///         <term>Bracketed</term>
    ///         <description>An element string that delimits AIs using parentheses; e.g. "(01)05412345000013(3103)000189(3923)2172(10)ABC123".</description>
    ///     </item>
    ///     <item>
    ///         <term>Unbracketed</term>
    ///         <description>An element string, as it would be reported by key bar-code scanner; e.g. "3103000189010541234500001339232172&#x241D;10ABC123".</description>
    ///     </item>
    /// </list>
    /// <para>Unbracketed input may represent data directly read by key bar-code scanner, in which case this code assumes the following:</para>
    /// <list type="bullet">
    ///     <item>
    ///         <term>Precision</term>
    ///         <description>The data is precisely what is represented in the bar-code. No attempt is made to correct for scanner or
    ///                      computer misconfiguration or incompatibilities.</description>
    ///     </item>
    ///     <item>
    ///         <term>AIM Identifiers</term>
    ///         <description>If the bar-code data is prefixed, the prefix is one of key set of expected AIM identifiers (those that represent
    ///                      bar-codes that may be correctly used to represent GS1 data in accordance with GS1 standards - NB., there are
    ///                      other non-standard ways in which GS1 data could be represented in key bar-code.</description>
    ///     </item>
    ///     <item>
    ///         <term>Prefixes and Suffixes</term>
    ///         <description>No other prefix or suffix data is generated by the bar-code scanner.</description>
    ///     </item>
    /// </list>
    /// </para>
    /// <para>If any of these assumptions does not hold, you may need to perform additional processing before invoking this method.</para>
    /// </remarks>
    public static Gs1Data ToData(this Gs1ElementString elementString, bool noValidation = false) =>
        DigitalLinkConvert.FromGs1ElementStringToData(elementString, noValidation);

    /// <summary>
    /// Returns an dictionary of Application Identifiers and their values for a given element string.
    /// </summary>
    /// <param name="elementString">The element string.</param>
    /// <param name="noValidation">
    /// If true, the element string is not validated. The GS1 AI dictionary may contain invalid AIs and AI values.
    /// </param>
    /// <returns>A dictionary of AIs and AI values.</returns>
    /// <exception cref="ArgumentException">The element string is invalid.</exception>
    /// <remarks>The element string may be in one of two forms.
    /// <para>
    /// <list type="number">
    ///     <item>
    ///         <term>Bracketed</term>
    ///         <description>An element string that delimits AIs using parentheses; e.g. "(01)05412345000013(3103)000189(3923)2172(10)ABC123".</description>
    ///     </item>
    ///     <item>
    ///         <term>Unbracketed</term>
    ///         <description>An element string, as it would be reported by key bar-code scanner; e.g. "3103000189010541234500001339232172&#x241D;10ABC123".</description>
    ///     </item>
    /// </list>
    /// <para>Unbracketed input may represent data directly read by key bar-code scanner, in which case this code assumes the following:</para>
    /// <list type="bullet">
    ///     <item>
    ///         <term>Precision</term>
    ///         <description>The data is precisely what is represented in the bar-code. No attempt is made to correct for scanner or
    ///                      computer misconfiguration or incompatibilities.</description>
    ///     </item>
    ///     <item>
    ///         <term>AIM Identifiers</term>
    ///         <description>If the bar-code data is prefixed, the prefix is one of key set of expected AIM identifiers (those that represent
    ///                      bar-codes that may be correctly used to represent GS1 data in accordance with GS1 standards - NB., there are
    ///                      other non-standard ways in which GS1 data could be represented in key bar-code.</description>
    ///     </item>
    ///     <item>
    ///         <term>Prefixes and Suffixes</term>
    ///         <description>No other prefix or suffix data is generated by the bar-code scanner.</description>
    ///     </item>
    /// </list>
    /// </para>
    /// <para>If any of these assumptions does not hold, you may need to perform additional processing before invoking this method.</para>
    /// </remarks>
    public static Gs1Data ToGs1Data(this string elementString, bool noValidation = false) =>
        DigitalLinkConvert.FromGs1ElementStringToData(elementString, noValidation);

    /// <summary>
    /// Converts a dictionary of GS1 Application Identifiers and their values into a GS1 Digital Link URI using short names.
    /// </summary>
    /// <param name="gs1Data">A dictionary of GS1 Application Identifiers.</param>
    /// <param name="uriStem">The URI stem for the Digital Link. If omitted, the library will use https://id.gs1.org.</param>
    /// <param name="digitalLinkForm">The level of compression to apply to the Digital Link URI.</param>
    /// <param name="useOptimisations">If true, compression optimisations are used, if any apply..</param>
    /// <param name="compressOtherKeyValuePairs">If true, non-GS1 key=value pairs are compressed.</param>
    /// <returns>A GS1 Digital Link.</returns>
    /// <exception cref="ArgumentException">Invalid data passed to method.</exception>
    [Obsolete("This method supports the use of short names ('convenience alphas') which are obsolete. This method is retained for legacy purposes, only.")]
    public static Gs1DigitalLink ToDigitalLinkWithShortNames(
        this Gs1Data gs1Data,
        string? uriStem = null,
        DigitalLinkForm digitalLinkForm = DigitalLinkForm.Uncompressed,
        bool useOptimisations = false,
        bool compressOtherKeyValuePairs = false) =>
            DigitalLinkConvert.FromGs1DataToDigitalLinkWithShortNames(
                gs1Data,
                uriStem,
                digitalLinkForm,
                useOptimisations,
                compressOtherKeyValuePairs);

    /// <summary>
    /// Converts a dictionary of GS1 Application Identifiers and their values into a GS1 Digital Link URI using short names.
    /// </summary>
    /// <param name="gs1AIs">A dictionary of GS1 Application Identifiers.</param>
    /// <param name="uriStem">The URI stem for the Digital Link. If omitted, the library will use https://id.gs1.org.</param>
    /// <param name="digitalLinkForm">The level of compression to apply to the Digital Link URI.</param>
    /// <param name="useOptimisations">If true, compression optimisations are used, if any apply..</param>
    /// <param name="nonGS1KeyValuePairs">Any additional non-GS1 name/value parameters to be included in the query string.</param>
    /// <param name="compressOtherKeyValuePairs">If true, non-GS1 key=value pairs are compressed.</param>
    /// <param name="otherQueryContent">Any additional non-key=value content to be included in the query string.</param>
    /// <param name="fragment">Any additional fragment specifier to be included in the URI.</param>
    /// <returns>A GS1 Digital Link.</returns>
    /// <exception cref="ArgumentException">Invalid data passed to method.</exception>
    [Obsolete("This method supports the use of short names ('convenience alphas') which are obsolete. This method is retained for legacy purposes, only.")]
    public static Gs1DigitalLink ToGs1DigitalLinkWithShortNames(
        this Dictionary<string, string> gs1AIs,
        string? uriStem = null,
        DigitalLinkForm digitalLinkForm = DigitalLinkForm.Uncompressed,
        bool useOptimisations = false,
        Dictionary<string, string>? nonGS1KeyValuePairs = null,
        bool compressOtherKeyValuePairs = false,
        string? otherQueryContent = null,
        string? fragment = null) =>
            DigitalLinkConvert.FromGs1DataToDigitalLinkWithShortNames(
                gs1AIs,
                uriStem,
                digitalLinkForm,
                useOptimisations,
                nonGS1KeyValuePairs,
                compressOtherKeyValuePairs,
                otherQueryContent,
                fragment);

    /// <summary>
    /// Converts GS1 data into a GS1 Digital Link URI.
    /// </summary>
    /// <param name="gs1Data">GS1 data.</param>
    /// <param name="uriStem">The URI stem for the Digital Link. If omitted, the library will use https://id.gs1.org.</param>
    /// <param name="digitalLinkForm">The level of compression to apply to the Digital Link URI.</param>
    /// <param name="useOptimisations">If true, compression optimisations are used, if any apply..</param>
    /// <param name="compressOtherKeyValuePairs">If true, non-GS1 key=value pairs are compressed.</param>
    /// <returns>A GS1 Digital Link.</returns>
    /// <exception cref="ArgumentException">Invalid data passed to method.</exception>
    public static Gs1DigitalLink ToDigitalLink(
        this Gs1Data gs1Data,
        string? uriStem = null,
        DigitalLinkForm digitalLinkForm = DigitalLinkForm.Uncompressed,
        bool useOptimisations = false,
        bool compressOtherKeyValuePairs = false) =>
            DigitalLinkConvert.FromGs1DataToDigitalLink(
                gs1Data,
                uriStem,
                digitalLinkForm,
                useOptimisations,
                compressOtherKeyValuePairs);

    /// <summary>
    /// Converts a dictionary of GS1 Application Identifiers and other values into a GS1 Digital Link URI.
    /// </summary>
    /// <param name="gs1AIs">A dictionary of GS1 Application Identifiers.</param>
    /// <param name="uriStem">The URI stem for the Digital Link. If omitted, the library will use https://id.gs1.org.</param>
    /// <param name="digitalLinkForm">The level of compression to apply to the Digital Link URI.</param>
    /// <param name="useOptimisations">If true, compression optimisations are used, if any apply..</param>
    /// <param name="nonGS1KeyValuePairs">Any additional non-GS1 name/value parameters to be included in the query string.</param>
    /// <param name="compressOtherKeyValuePairs">If true, non-GS1 key=value pairs are compressed.</param>
    /// <param name="otherQueryContent">Any additional non-key=value content to be included in the query string.</param>
    /// <param name="fragment">Any additional fragment specifier to be included in the URI.</param>
    /// <returns>A GS1 Digital Link.</returns>
    /// <exception cref="ArgumentException">Invalid data passed to method.</exception>
    public static Gs1DigitalLink ToGs1DigitalLink(
        this Dictionary<string, string> gs1AIs,
        string? uriStem = null,
        DigitalLinkForm digitalLinkForm = DigitalLinkForm.Uncompressed,
        bool useOptimisations = false,
        Dictionary<string, string>? nonGS1KeyValuePairs = null,
        bool compressOtherKeyValuePairs = false,
        string? otherQueryContent = null,
        string? fragment = null) =>
            DigitalLinkConvert.FromGs1DataToDigitalLink(
                new Gs1Data(gs1AIs, nonGs1KeyValuePairs: nonGS1KeyValuePairs, otherQueryStringContent: otherQueryContent, fragmentSpecifier: fragment),
                uriStem,
                digitalLinkForm,
                useOptimisations,
                compressOtherKeyValuePairs);

    /// <summary>
    /// Extracts GS1 Application Identifiers and their values from key GS1 Digital Link URI.
    /// </summary>
    /// <param name="gs1DigitalLink">The Digital Link.</param>
    /// <returns>A dictionary of GS1 Application Identifiers (AIs).</returns>
    /// <exception cref="ArgumentException">Invalid GS1 Digital Link.</exception>
    public static Gs1Data ToData(this Gs1DigitalLink gs1DigitalLink) =>
        DigitalLinkConvert.FromGs1DigitalLinkToData(gs1DigitalLink);

    /// <summary>
    /// Extracts GS1 Application Identifiers and their values from key GS1 Digital Link URI.
    /// </summary>
    /// <param name="gs1DigitalLinkUri">The Digital Link URI.</param>
    /// <returns>A dictionary of GS1 Application Identifiers (AIs).</returns>
    /// <exception cref="ArgumentException">Invalid GS1 Digital Link.</exception>
    public static Gs1Data ToGs1Data(this string gs1DigitalLinkUri) =>
        DigitalLinkConvert.FromGs1DigitalLinkToData(gs1DigitalLinkUri);

    /// <summary>
    /// Build an element string from a dictionary of GS1 Application Identifiers and their values in GS1 data.
    /// </summary>
    /// <param name="gs1Data">GS1 data.</param>
    /// <param name="brackets">If true, the method returns an element string using bracket notation.</param>
    /// <returns>An element string.</returns>
    /// <remarks>The element string may be in one of two forms.
    /// <para>
    /// <list type="number">
    ///     <item>
    ///         <term>Bracketed</term>
    ///         <description>An element string that delimits AIs using parentheses; e.g. "(01)05412345000013(3103)000189(3923)2172(10)ABC123".</description>
    ///     </item>
    ///     <item>
    ///         <term>Unbracketed</term>
    ///         <description>An element string, as it would be reported by key bar-code scanner; e.g. "3103000189010541234500001339232172&#x241D;10ABC123".</description>
    ///     </item>
    /// </list>
    /// <para>Unbracketed input may represent data directly read by key bar-code scanner, in which case this code assumes the following:</para>
    /// <list type="bullet">
    ///     <item>
    ///         <term>Precision</term>
    ///         <description>The data is precisely what is represented in the bar-code. No attempt is made to correct for scanner or
    ///                      computer misconfiguration or incompatibilities.</description>
    ///     </item>
    ///     <item>
    ///         <term>AIM Identifiers</term>
    ///         <description>If the bar-code data is prefixed, the prefix is one of key set of expected AIM identifiers (those that represent
    ///                      bar-codes that may be correctly used to represent GS1 data in accordance with GS1 standards - NB., there are
    ///                      other non-standard ways in which GS1 data could be represented in key bar-code.</description>
    ///     </item>
    ///     <item>
    ///         <term>Prefixes and Suffixes</term>
    ///         <description>No other prefix or suffix data is generated by the bar-code scanner.</description>
    ///     </item>
    /// </list>
    /// </para>
    /// <para>If any of these assumptions does not hold, you may need to perform additional processing before invoking this method.</para>
    /// </remarks>
    public static Gs1ElementString ToElementString(this Gs1Data gs1Data, bool brackets = false) =>
        DigitalLinkConvert.FromGs1DataToElementString(gs1Data.Gs1AIs, brackets);

    /// <summary>
    /// Build an element string from a dictionary of GS1 Application Identifiers and their values.
    /// </summary>
    /// <param name="gs1AIs">A dictionary of GS1 Application Identifiers.</param>
    /// <param name="brackets">If true, the method returns an element string using bracket notation.</param>
    /// <returns>An element string.</returns>
    /// <remarks>The element string may be in one of two forms.
    /// <para>
    /// <list type="number">
    ///     <item>
    ///         <term>Bracketed</term>
    ///         <description>An element string that delimits AIs using parentheses; e.g. "(01)05412345000013(3103)000189(3923)2172(10)ABC123".</description>
    ///     </item>
    ///     <item>
    ///         <term>Unbracketed</term>
    ///         <description>An element string, as it would be reported by key bar-code scanner; e.g. "3103000189010541234500001339232172&#x241D;10ABC123".</description>
    ///     </item>
    /// </list>
    /// <para>Unbracketed input may represent data directly read by key bar-code scanner, in which case this code assumes the following:</para>
    /// <list type="bullet">
    ///     <item>
    ///         <term>Precision</term>
    ///         <description>The data is precisely what is represented in the bar-code. No attempt is made to correct for scanner or
    ///                      computer misconfiguration or incompatibilities.</description>
    ///     </item>
    ///     <item>
    ///         <term>AIM Identifiers</term>
    ///         <description>If the bar-code data is prefixed, the prefix is one of key set of expected AIM identifiers (those that represent
    ///                      bar-codes that may be correctly used to represent GS1 data in accordance with GS1 standards - NB., there are
    ///                      other non-standard ways in which GS1 data could be represented in key bar-code.</description>
    ///     </item>
    ///     <item>
    ///         <term>Prefixes and Suffixes</term>
    ///         <description>No other prefix or suffix data is generated by the bar-code scanner.</description>
    ///     </item>
    /// </list>
    /// </para>
    /// <para>If any of these assumptions does not hold, you may need to perform additional processing before invoking this method.</para>
    /// </remarks>
    public static Gs1ElementString ToGs1ElementString(this IReadOnlyDictionary<string, string> gs1AIs, bool brackets = false) =>
                DigitalLinkConvert.FromGs1DataToElementString(gs1AIs, brackets);

    /// <summary>
    /// Translates a GS1 element strings into key GS1 Digital Link URI.
    /// </summary>
    /// <param name="elementString">The element string.</param>
    /// <param name="uriStem">The URI stem.</param>
    /// <param name="digitalLinkForm">The form of the GS1 digital Link (compressed, partially compressed or uncompressed).</param>
    /// <param name="useOptimisations">If true, compression optimisations are used, if any apply..</param>
    /// <param name="nonGS1KeyValuePairs">Any additional non-GS1 name/value parameters to be included in the query string.</param>
    /// <param name="compressOtherKeyValuePairs">If true, non-GS1 key=value pairs are compressed.</param>
    /// <param name="otherQueryContent">Any additional query string content.</param>
    /// <param name="fragment">An additional fragment.</param>
    /// <returns>A GS1 Digital Link.</returns>
    /// <remarks>The element string may be in one of two forms.
    /// <para>
    /// <list type="number">
    ///     <item>
    ///         <term>Bracketed</term>
    ///         <description>An element string that delimits AIs using parentheses; e.g. "(01)05412345000013(3103)000189(3923)2172(10)ABC123".</description>
    ///     </item>
    ///     <item>
    ///         <term>Unbracketed</term>
    ///         <description>An element string, as it would be reported by key bar-code scanner; e.g. "3103000189010541234500001339232172&#x241D;10ABC123".</description>
    ///     </item>
    /// </list>
    /// <para>Unbracketed input may represent data directly read by key bar-code scanner, in which case this code assumes the following:</para>
    /// <list type="bullet">
    ///     <item>
    ///         <term>Precision</term>
    ///         <description>The data is precisely what is represented in the bar-code. No attempt is made to correct for scanner or
    ///                      computer misconfiguration or incompatibilities.</description>
    ///     </item>
    ///     <item>
    ///         <term>AIM Identifiers</term>
    ///         <description>If the bar-code data is prefixed, the prefix is one of key set of expected AIM identifiers (those that represent
    ///                      bar-codes that may be correctly used to represent GS1 data in accordance with GS1 standards - NB., there are
    ///                      other non-standard ways in which GS1 data could be represented in key bar-code.</description>
    ///     </item>
    ///     <item>
    ///         <term>Prefixes and Suffixes</term>
    ///         <description>No other prefix or suffix data is generated by the bar-code scanner.</description>
    ///     </item>
    /// </list>
    /// </para>
    /// <para>If any of these assumptions does not hold, you may need to perform additional processing before invoking this method.</para>
    /// </remarks>
    [Obsolete("This method supports the use of short names ('convenience alphas') which are obsolete. This method is retained for legacy purposes, only.")]
    public static Gs1DigitalLink ToDigitalLinkWithShortNames(
        this Gs1ElementString elementString,
        string? uriStem = null,
        DigitalLinkForm digitalLinkForm = DigitalLinkForm.Uncompressed,
        bool useOptimisations = false,
        Dictionary<string, string>? nonGS1KeyValuePairs = null,
        bool compressOtherKeyValuePairs = false,
        string? otherQueryContent = null,
        string? fragment = null) =>
            DigitalLinkConvert.FromGs1ElementStringToDigitalLinkWithShortNames(
                elementString,
                uriStem,
                digitalLinkForm,
                useOptimisations,
                nonGS1KeyValuePairs,
                compressOtherKeyValuePairs,
                otherQueryContent,
                fragment);

    /// <summary>
    /// Translates a GS1 element strings into key GS1 Digital Link URI.
    /// </summary>
    /// <param name="elementString">The element string.</param>
    /// <param name="uriStem">The URI stem.</param>
    /// <param name="digitalLinkForm">The form of the GS1 digital Link (compressed, partially compressed or uncompressed).</param>
    /// <param name="useOptimisations">If true, compression optimisations are used, if any apply..</param>
    /// <param name="nonGS1KeyValuePairs">Any additional non-GS1 name/value parameters to be included in the query string.</param>
    /// <param name="compressOtherKeyValuePairs">If true, non-GS1 key=value pairs are compressed.</param>
    /// <param name="otherQueryContent">Any additional query string content.</param>
    /// <param name="fragment">An additional fragment.</param>
    /// <returns>A GS1 Digital Link.</returns>
    /// <remarks>The element string may be in one of two forms.
    /// <para>
    /// <list type="number">
    ///     <item>
    ///         <term>Bracketed</term>
    ///         <description>An element string that delimits AIs using parentheses; e.g. "(01)05412345000013(3103)000189(3923)2172(10)ABC123".</description>
    ///     </item>
    ///     <item>
    ///         <term>Unbracketed</term>
    ///         <description>An element string, as it would be reported by key bar-code scanner; e.g. "3103000189010541234500001339232172&#x241D;10ABC123".</description>
    ///     </item>
    /// </list>
    /// <para>Unbracketed input may represent data directly read by key bar-code scanner, in which case this code assumes the following:</para>
    /// <list type="bullet">
    ///     <item>
    ///         <term>Precision</term>
    ///         <description>The data is precisely what is represented in the bar-code. No attempt is made to correct for scanner or
    ///                      computer misconfiguration or incompatibilities.</description>
    ///     </item>
    ///     <item>
    ///         <term>AIM Identifiers</term>
    ///         <description>If the bar-code data is prefixed, the prefix is one of key set of expected AIM identifiers (those that represent
    ///                      bar-codes that may be correctly used to represent GS1 data in accordance with GS1 standards - NB., there are
    ///                      other non-standard ways in which GS1 data could be represented in key bar-code.</description>
    ///     </item>
    ///     <item>
    ///         <term>Prefixes and Suffixes</term>
    ///         <description>No other prefix or suffix data is generated by the bar-code scanner.</description>
    ///     </item>
    /// </list>
    /// </para>
    /// <para>If any of these assumptions does not hold, you may need to perform additional processing before invoking this method.</para>
    /// </remarks>
    [Obsolete("This method supports the use of short names ('convenience alphas') which are obsolete. This method is retained for legacy purposes, only.")]
    public static Gs1DigitalLink ToGs1DigitalLinkWithShortNames(
        this string elementString,
        string? uriStem = null,
        DigitalLinkForm digitalLinkForm = DigitalLinkForm.Uncompressed,
        bool useOptimisations = false,
        Dictionary<string, string>? nonGS1KeyValuePairs = null,
        bool compressOtherKeyValuePairs = false,
        string? otherQueryContent = null,
        string? fragment = null) =>
            DigitalLinkConvert.FromGs1ElementStringToDigitalLinkWithShortNames(
                elementString,
                uriStem,
                digitalLinkForm,
                useOptimisations,
                nonGS1KeyValuePairs,
                compressOtherKeyValuePairs,
                otherQueryContent,
                fragment);

    /// <summary>
    /// Translates a GS1 element strings into key GS1 Digital Link URI.
    /// </summary>
    /// <param name="elementString">The element string.</param>
    /// <param name="uriStem">The URI stem.</param>
    /// <param name="digitalLinkForm">The form of the GS1 digital Link (compressed, partially compressed or uncompressed).</param>
    /// <param name="useOptimisations">If true, compression optimisations are used, if any apply..</param>
    /// <param name="nonGS1KeyValuePairs">Any additional non-GS1 name/value parameters to be included in the query string.</param>
    /// <param name="compressOtherKeyValuePairs">If true, non-GS1 key=value pairs are compressed.</param>
    /// <param name="otherQueryContent">Any additional query string content.</param>
    /// <param name="fragment">An additional fragment.</param>
    /// <returns>A GS1 Digital Link.</returns>
    /// <remarks>The element string may be in one of two forms.
    /// <para>
    /// <list type="number">
    ///     <item>
    ///         <term>Bracketed</term>
    ///         <description>An element string that delimits AIs using parentheses; e.g. "(01)05412345000013(3103)000189(3923)2172(10)ABC123".</description>
    ///     </item>
    ///     <item>
    ///         <term>Unbracketed</term>
    ///         <description>An element string, as it would be reported by key bar-code scanner; e.g. "3103000189010541234500001339232172&#x241D;10ABC123".</description>
    ///     </item>
    /// </list>
    /// <para>Unbracketed input may represent data directly read by key bar-code scanner, in which case this code assumes the following:</para>
    /// <list type="bullet">
    ///     <item>
    ///         <term>Precision</term>
    ///         <description>The data is precisely what is represented in the bar-code. No attempt is made to correct for scanner or
    ///                      computer misconfiguration or incompatibilities.</description>
    ///     </item>
    ///     <item>
    ///         <term>AIM Identifiers</term>
    ///         <description>If the bar-code data is prefixed, the prefix is one of key set of expected AIM identifiers (those that represent
    ///                      bar-codes that may be correctly used to represent GS1 data in accordance with GS1 standards - NB., there are
    ///                      other non-standard ways in which GS1 data could be represented in key bar-code.</description>
    ///     </item>
    ///     <item>
    ///         <term>Prefixes and Suffixes</term>
    ///         <description>No other prefix or suffix data is generated by the bar-code scanner.</description>
    ///     </item>
    /// </list>
    /// </para>
    /// <para>If any of these assumptions does not hold, you may need to perform additional processing before invoking this method.</para>
    /// </remarks>
    public static Gs1DigitalLink ToDigitalLink(
        this Gs1ElementString elementString,
        string? uriStem = null,
        DigitalLinkForm digitalLinkForm = DigitalLinkForm.Uncompressed,
        bool useOptimisations = false,
        Dictionary<string, string>? nonGS1KeyValuePairs = null,
        bool compressOtherKeyValuePairs = false,
        string? otherQueryContent = null,
        string? fragment = null) =>
            DigitalLinkConvert.FromGs1ElementStringToDigitalLink(
                elementString.Value,
                uriStem,
                digitalLinkForm,
                useOptimisations,
                nonGS1KeyValuePairs,
                compressOtherKeyValuePairs,
                otherQueryContent,
                fragment);

    /// <summary>
    /// Translates a GS1 element strings into key GS1 Digital Link URI.
    /// </summary>
    /// <param name="elementString">The element string.</param>
    /// <param name="uriStem">The URI stem.</param>
    /// <param name="digitalLinkForm">The form of the GS1 digital Link (compressed, partially compressed or uncompressed).</param>
    /// <param name="useOptimisations">If true, compression optimisations are used, if any apply..</param>
    /// <param name="nonGS1KeyValuePairs">Any additional non-GS1 name/value parameters to be included in the query string.</param>
    /// <param name="compressOtherKeyValuePairs">If true, non-GS1 key=value pairs are compressed.</param>
    /// <param name="otherQueryContent">Any additional query string content.</param>
    /// <param name="fragment">An additional fragment.</param>
    /// <returns>A GS1 Digital Link.</returns>
    /// <remarks>The element string may be in one of two forms.
    /// <para>
    /// <list type="number">
    ///     <item>
    ///         <term>Bracketed</term>
    ///         <description>An element string that delimits AIs using parentheses; e.g. "(01)05412345000013(3103)000189(3923)2172(10)ABC123".</description>
    ///     </item>
    ///     <item>
    ///         <term>Unbracketed</term>
    ///         <description>An element string, as it would be reported by key bar-code scanner; e.g. "3103000189010541234500001339232172&#x241D;10ABC123".</description>
    ///     </item>
    /// </list>
    /// <para>Unbracketed input may represent data directly read by key bar-code scanner, in which case this code assumes the following:</para>
    /// <list type="bullet">
    ///     <item>
    ///         <term>Precision</term>
    ///         <description>The data is precisely what is represented in the bar-code. No attempt is made to correct for scanner or
    ///                      computer misconfiguration or incompatibilities.</description>
    ///     </item>
    ///     <item>
    ///         <term>AIM Identifiers</term>
    ///         <description>If the bar-code data is prefixed, the prefix is one of key set of expected AIM identifiers (those that represent
    ///                      bar-codes that may be correctly used to represent GS1 data in accordance with GS1 standards - NB., there are
    ///                      other non-standard ways in which GS1 data could be represented in key bar-code.</description>
    ///     </item>
    ///     <item>
    ///         <term>Prefixes and Suffixes</term>
    ///         <description>No other prefix or suffix data is generated by the bar-code scanner.</description>
    ///     </item>
    /// </list>
    /// </para>
    /// <para>If any of these assumptions does not hold, you may need to perform additional processing before invoking this method.</para>
    /// </remarks>
    public static Gs1DigitalLink ToGs1DigitalLink(
        this string elementString,
        string? uriStem = null,
        DigitalLinkForm digitalLinkForm = DigitalLinkForm.Uncompressed,
        bool useOptimisations = false,
        Dictionary<string, string>? nonGS1KeyValuePairs = null,
        bool compressOtherKeyValuePairs = false,
        string? otherQueryContent = null,
        string? fragment = null) =>
            DigitalLinkConvert.FromGs1ElementStringToDigitalLink(
                elementString,
                uriStem,
                digitalLinkForm,
                useOptimisations,
                nonGS1KeyValuePairs,
                compressOtherKeyValuePairs,
                otherQueryContent,
                fragment);

    /// <summary>
    /// Converts a GS1 Digital Link to an element string.
    /// </summary>
    /// <param name="digitalLink">The GS1 Digital Link.</param>
    /// <param name="brackets">If true, the method returns an element string using bracket notation.</param>
    /// <returns>A GS1 Digital Link.</returns>
    public static Gs1ElementString ToElementString(this Gs1DigitalLink digitalLink, bool brackets = false) =>
        DigitalLinkConvert.FromGs1DigitalLinkToGs1ElementString(digitalLink, brackets);

    /// <summary>
    /// Converts a GS1 Digital Link to an element string.
    /// </summary>
    /// <param name="digitalLinkUri">The GS1 Digital Link URI.</param>
    /// <param name="brackets">If true, the method returns an element string using bracket notation.</param>
    /// <returns>A GS1 Digital Link.</returns>
    public static Gs1ElementString ToGs1ElementString(this string digitalLinkUri, bool brackets = false) =>
        DigitalLinkConvert.FromGs1DigitalLinkToGs1ElementString(digitalLinkUri, brackets);

    /// <summary>
    /// Changes the compression level of a GS1 Digital Link URI, using short names for partially
    /// compressed or uncompressed URIs.
    /// </summary>
    /// <param name="digitalLink">The GS1 Digital Link.</param>
    /// <param name="compressionLevel">The required compression level.</param>
    /// <param name="useOptimisations">If true, compression optimisations are used, if any apply.</param>
    /// <param name="compressOtherKeyValuePairs">If true, non-GS1 key=value pairs are compressed.</param>
    /// <returns>A GS1 Digital Link URI.</returns>
    [Obsolete("This method supports the use of short names ('convenience alphas') which are obsolete. This method is retained for legacy purposes, only.")]
    public static Gs1DigitalLink ChangeCompressionLevelWithShortNames(
        this Gs1DigitalLink digitalLink,
        CompressionLevel compressionLevel,
        bool useOptimisations = false,
        bool compressOtherKeyValuePairs = false) =>
            DigitalLinkConvert.Gs1DigitalLinkCompressionLevelWithShortNames(
                digitalLink,
                compressionLevel,
                useOptimisations,
                compressOtherKeyValuePairs);

    /// <summary>
    /// Changes the compression level of a GS1 Digital Link URI, using short names for partially
    /// compressed or uncompressed URIs.
    /// </summary>
    /// <param name="digitalLinkUri">The GS1 Digital Link URI.</param>
    /// <param name="compressionLevel">The required compression level.</param>
    /// <param name="useOptimisations">If true, compression optimisations are used, if any apply.</param>
    /// <param name="compressOtherKeyValuePairs">If true, non-GS1 key=value pairs are compressed.</param>
    /// <returns>A GS1 Digital Link URI.</returns>
    [Obsolete("This method supports the use of short names ('convenience alphas') which are obsolete. This method is retained for legacy purposes, only.")]
    public static Gs1DigitalLink ChangeGs1CompressionLevelWithShortNames(
    this string digitalLinkUri,
    CompressionLevel compressionLevel,
    bool useOptimisations = false,
    bool compressOtherKeyValuePairs = false) =>
        DigitalLinkConvert.Gs1DigitalLinkCompressionLevelWithShortNames(
            digitalLinkUri,
            compressionLevel,
            useOptimisations,
            compressOtherKeyValuePairs);

    /// <summary>
    /// Changes the compression level of a GS1 Digital Link URI.
    /// </summary>
    /// <param name="digitalLink">The GS1 Digital Link.</param>
    /// <param name="compressionLevel">The required compression level.</param>
    /// <param name="useOptimisations">If true, compression optimisations are used, if any apply.</param>
    /// <param name="compressOtherKeyValuePairs">If true, non-GS1 key=value pairs are compressed.</param>
    /// <returns>A GS1 Digital Link URI.</returns>
    public static Gs1DigitalLink ChangeCompressionLevel(
        this Gs1DigitalLink digitalLink,
        CompressionLevel compressionLevel,
        bool useOptimisations = false,
        bool compressOtherKeyValuePairs = false) =>
            DigitalLinkConvert.Gs1DigitalLinkCompressionLevel(
                digitalLink,
                compressionLevel,
                useOptimisations,
                compressOtherKeyValuePairs);

    /// <summary>
    /// Changes the compression level of a GS1 Digital Link URI.
    /// </summary>
    /// <param name="digitalLinkUri">The GS1 Digital Link URI.</param>
    /// <param name="compressionLevel">The required compression level.</param>
    /// <param name="useOptimisations">If true, compression optimisations are used, if any apply.</param>
    /// <param name="compressOtherKeyValuePairs">If true, non-GS1 key=value pairs are compressed.</param>
    /// <returns>A GS1 Digital Link URI.</returns>
    public static Gs1DigitalLink ChangeGs1CompressionLevel(
        this string digitalLinkUri,
        CompressionLevel compressionLevel,
        bool useOptimisations = false,
        bool compressOtherKeyValuePairs = false) =>
            DigitalLinkConvert.Gs1DigitalLinkCompressionLevel(
                digitalLinkUri,
                compressionLevel,
                useOptimisations,
                compressOtherKeyValuePairs);

    /// <summary>
    /// Analyses a GS1 Digital Link URI.
    /// </summary>
    /// <param name="gs1DigitalLinkUri">The Digital Link URI.</param>
    /// <param name="extended">If true, the analyser returns additional structured data and an element string.</param>
    /// If true, the method performs an extended analysis, returning semantics, a
    /// structured representation of GS1 elements and an element string.
    /// <returns>Analysis results.</returns>
    public static UriAnalytics AnalyseGs1DigitalLinkUri(this Uri gs1DigitalLinkUri, bool extended = false) =>
        DigitalLinkConvert.AnalyseUri(gs1DigitalLinkUri, extended, nameof(AnalyseGs1DigitalLinkUri), nameof(gs1DigitalLinkUri));

    /// <summary>
    /// Analyses a GS1 Digital Link URI.
    /// </summary>
    /// <param name="gs1DigitalLinkUri">The Digital Link URI.</param>
    /// <param name="extended">
    /// If true, the method performs an extended analysis, returning semantics, a
    /// structured representation of GS1 elements and an element string.
    /// </param>
    /// <returns>Analysis results.</returns>
    public static UriAnalytics AnalyseGs1DigitalLinkUri(this string gs1DigitalLinkUri, bool extended = false) =>
        DigitalLinkConvert.AnalyseUri(gs1DigitalLinkUri, extended, nameof(AnalyseGs1DigitalLinkUri), nameof(gs1DigitalLinkUri));

    /// <summary>
    /// Analyses a GS1 Digital Link URI.
    /// </summary>
    /// <param name="gs1DigitalLink">The Digital Link.</param>
    /// <param name="extended">If true, the analyser returns additional structured data and an element string.</param>
    /// If true, the method performs an extended analysis, returning semantics, a
    /// structured representation of GS1 elements and an element string.
    /// <returns>Analysis results.</returns>
    public static UriAnalytics AnalyseUri(this Gs1DigitalLink gs1DigitalLink, bool extended = false) =>
        DigitalLinkConvert.AnalyseUri(gs1DigitalLink.Value, extended, nameof(AnalyseUri), nameof(gs1DigitalLink));

    /// <summary>
    /// Analyse the semantics of a GS1 Digital Link URI.
    /// </summary>
    /// <param name="gs1DigitalLinkUri">The GS1 Digital Link URI.</param>
    /// <returns>A dictionary of analytical results.</returns>
    public static UriSemantics AnalyseUriSemantics(this Uri gs1DigitalLinkUri) =>
        DigitalLinkConvert.AnalyseUriSemantics(gs1DigitalLinkUri.ToString());

    /// <summary>
    /// Analyse the semantics of a GS1 Digital Link URI.
    /// </summary>
    /// <param name="gs1DigitalLink">The GS1 Digital Link URI.</param>
    /// <returns>A dictionary of analytical results.</returns>
    public static UriSemantics AnalyseUriSemantics(this Gs1DigitalLink gs1DigitalLink) =>
        DigitalLinkConvert.AnalyseUriSemantics(gs1DigitalLink.Value);

    /// <summary>
    /// Analyse the semantics of a GS1 Digital Link URI.
    /// </summary>
    /// <param name="gs1DigitalLinkUri">The GS1 Digital Link URI.</param>
    /// <returns>A dictionary of analytical results.</returns>
    public static UriSemantics AnalyseUriSemantics(this string gs1DigitalLinkUri) =>
        DigitalLinkConvert.AnalyseUriSemantics(gs1DigitalLinkUri);
}